---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBHVWJX+0W4RPZ7VIA8dIs49tnHga/Imc/M7nxTS95sxwdMrRQIqJFu7SL6ph0dbSFYeL2fq7lD0ZRrlmyVBO9pjoIo3b3WRyMxrzAtBthcwRtH6oL2P/Cg2wk2f/oN5MYXUiXnO0Fn8ithW+dgM0i4O4W0bm/6v2uuCZOCq/R384c6UXIVG2u4c+m5E91Sj0BMlUAZeb3vL8/9SalBk3k1b5HwMRdvqq76rs+AbTbYuKLQ8wYaK5lPRc3iXXPOQXrfR6dlJbHnwNgYPyKaYF7GcIGle/X2+dQ0QZVz/1GFq64eY6A+q6wdoGapSNcxKvP1NWP7DT8S3jjaOqWhzyGGyPkw9HIcKfHDAmG0CtsuRMoJ818+H3AzHg3ioVxzAPbJ5hG7uOiIxg1808QO1xKS8B/5m5ZhzESW8sCySWhIGhSmOvTptuqvJrl9V3RsLAwLTGEJiYGDR4HbSNykbgVqEcY7bwqisjVxVkrnbO4AAuM5df4KbfrVK4moYx0LByp6XH7i0HsFFdc2irqvkfSD8cL04FG3ojHeQMo9fNsqR0i/jli4BpGTY5E70bL2zN38ScUcd69YAVOgDchlS2TRtZgDBnD/oDbyUScZ+B3moC8db0Xe9gGxtMvM5srn1hPykZynVzErzoUNnWVE+s523nrcCZmlqKllorw4b4pV2r0atsmmLBp3o+vpYMLdWn8aciM8cCEY6ZcFsfbO7ASMm/UfTrwM4LO1PIUgFt2FwSrEPI6K3oXoT6/glCTImB0MImOmcA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
