---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB9ZuP3uJzDg4Gfh9usL9Y4aWHW79XFe1lNwnaWlclBp4OmpiNuumhi6ArcRQhZoDEZs6xnNFR1YhwSxsrdGiNHoHiZzlPapsCjmtiISs8lRAobVFpPz+vbRpikM7sPYrxAbqtaaNDsxhL/7W7NP5ulCOnYXzZhupmT5FtRyq2Gc1YXOTRilTJ5+NMaIvkQk0Sao2kGQla/y+ZIXrgBpwKBg09FAvqDQ2RppJicVByUuvLw0M/mUzvujMSoe9g9oBFPxQAJoEy5sLbRZz8CYIidn3MsY7owyiOaxxU4M9LOgLpasCpadaUI0VwRaBVApI5iUPtwaGQRYbXkpBcrnsvcuVkHWTyPK1ULRHHWEXVS/sFT623Wzj0Hr+MLSSgasysODSK8Ro7kCnvxMyfhyEEPcDkAKBNeHu49itPqmjmpmAK0itLD375hPnzlPJfckaPVtM8JVHKTNX7WqqlKgWnlB0WBzS/bK3U7m53V5MEBU3CdYm4qUnD6XKPz3mipTPFOWkABToPM/rMZ53c23ukiykOxzyN3GIdAjuWZrCcmWttSWOad5pyV7j8z/ayrwTgNK4rnTR/rHyzdsGQBj9qcQwpoQkf4s+kmoWnkNlT/tDNnqrmAtOtd9cztVZNsXKTa6EAhHR6eAsN9MFXmqPxoBICxEYLglUrqyLXVEQCjF8RkP/22bMIQH7yQSXQAWx7MCU0XfznCYHQt8T2x5z9W69VTxDL7XDXogUHces2bVH0vdDuTv1TLkMXqko5mRT69uwd06A==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
