---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCfxoUagzkoHrrvyt2Ile3BQy5bbJMBK8mE2NioGzctWS9z8ALxxqDYzrYL29FQV8aE/fQY3VaVhBCURp8U+n9yOFNPTe+SwpoAPaxh+XfQkpWevFJZsg/L6co9k8MNIy5F/QHf4ZhPg8Fb/yxVQjmRjKnNEXkCwg6yeD6lJc7vztvBOuaDxsQvzkI734I/rEJ6ytW8ERTavXpgwsbsMBtvzCZovIM6vWOWXzsuWHtK5iYD2NsR4/augvXoWBWkRUMSocMczkdDdXmUH3dTjvfZR5KCXrz18svSS0aXUBNjGGUt99MQDTix+KcA779T6D3rsU6eTgyJc13m9Un9yy3QVkr2gP2LY+j07WmCnew18BCTeEKTOyhanu7N1BjmJ2RY+piBsModoLdAR9g4XWsYzfHva1cYEfMhtccra9OPHdLgXeN/3C3PiDRjqREzFy46319y97MFzd/fc+wERhIv3txFTMp4MXDucTLgofj+lAVVC6b0/kDSUy7hqQK+bLuGktN2Pjc1pwwMw7AujNwS7cRKjvbBlczOqXcfNBNy8JaILLKHXlQ2FDCN9z4N+jkytp16OJKtIYjNEtLRPtKBOh0XtcoeFTuCE7bQKGUHY3g+Gf2nyTqiQODRHBxRi47ZRBNX/jG35DP16dPlGFZwRQ+JnbjJlnxx6oFqaCRwR2Fc3R/mZ5bZ5+ENWJW3zRD/5sSp1c3c0OouSkos+8aXtFDiAf3L7UjNwm5pOJk3TEozjGyfgepdrR6caDZivTjyaJpVpQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
