---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgCfpdHWwMr1HXZ2nKfcyTn4qwROUA2zy/OaWgQxOTG5SppXEJhHt9U44wuC8AWetuvzWQien/ctqaxl8R80AkhJvMlc5acaerrZ5midxm/DdrSa1ykVwuwiJLsdvLGqXJFUPuSNh8sIpRNO8HW1RuYLRSg4x9XADq+/s5Bb6JZxnXPOZ9XpCYpudX9/csJPLeymg9At8SFXBya+03gjbDI+MJ2VcGweHGTc01efi6oj8c03oos3L76Dy4kvVV64qNdJ25x2+h1mTv9ch+N13YbWi0VfGybYOax1cGzFx88B1g5KnSqaV9Nm7APXJ8sVuDmeKwmgvceX2tkfDqB4X2Edf2u9+3JJ8G4wldkuiGhUWheCbMCdJF5GsquRJUU1LRRP01juzG+fPD0+exVw2gJcmDt8HXlLxqXYpknFqKTDtWy5BgEsf0UrnYYJbJeKlxuoKuE6QLFhMZ48p+6d9nlNz1bocOr3ZVrGw07ZaTCAgr20DokdJaAQ3+RC0sFcw+2bFzfmFj6s/XTFmYBSZ4f4v+Dfpo/Ewx55kcyfNsW57mf9naIrTy9WxshaqxYP5zh1NxI7aDDNVZJuRCdBzD1j2Sks6CHdEoZfFtZmUgxgkKua7mXluv7Y/0kQiIJ5e3hmY+cQUm/19/8vJQxMZ5tz/NV+M0hRprSM3h5pWTAJef+ApguUcsuzNqCXP1pAhQb2Ov2m2tdHT92y6stgPt3jBFu7iOmBkosIkcrE9ROw8w==
    AUTHENTIK_SECRET_KEY: AgCnivJJHENfqDqQ4OywZUD91wN2eKSvSqBmM7eWbGtzZ3lppgb79LnwpkrqZy4+wDU75Sl2h5oEgpkwRzldTWKWzck88FwaU+71+wF62KkIuaOoo7ZTjGH7qksr/yZ0Z5WRL/fratU5THS401UI9pJDRK49eZob0I6v/r3NA4UWxVY/20qmFnm6vlofJSqYsYnClE4GB7M5QklYTmkoa433GAOtMSJcbGX83LF9ifXfw/ATpGU7yXkhfJcA4vGhoFQCId4gcS020g911jUk9YbxsyKIcsmP6ffgduK+FqNl7l/y11sGECg0It5nE7vclTpyuRn40lqXWCMc/9j5nJTWe3PFveKyOAxHpsqvdIfzroTsSXr6pYAzeGPxRX4Z1bd4IXQq+5en9KYG9VoMp/uOeyuah7u4t8X6M9k09NIpcjhnysVhANxOUysFc4dhcQPWNbfRN6d3LbBc8llWg5NoqXC3OjWqGxmJKrMWxM+Zu+/rTfJeqFcDJ3U9IlraWojf0Myz2AKoGxriJwInFxsEztmMvJUkVEH0Ne1WwjcS6FLI08hqp5heoCQ0MMe/5HwTjiUCoZImUXqlaj7z8KejorgLv/MoUMZkgatR13M6DkRo0oXO0eMb+QZgy52qLT8dwR2fSVwxLA+FZqzL/w4uoRvvSkYekQLBc+5U93qmQ/VQtNIfkh8QB1XrXRKI+1RXdrlKfhtIKtj9W8US16KBz0cJSLzezjlsX+Lqefr2jg==
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
