---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgBMi0JNWLskn/H+jJZa9G1FxNDYkjAxUI+P+6dsRToh95vd6lzm2mN2lBZWvSHLmaqQBAYaN/3gAJ5Vgk3l9o3FZIkvpAnc5hgqV6SwmVm1F69uDndPDCE4pXu4bywsTyk1Slyw+o2c+pjyDZz/6JjpzBr+UMzCfkcY2uo3i9KO9kA/onK4PX6UnVyDxvhZs6cYfApI69kUxd7pv+jfj5sOA03Ww/Yr73oq3RmrSxVwIQVE/AiN6ZvOEUUK07jvjuyWHz0uzUjCSdfuB6lR3xzbpn+CgXRBXEJGsYCsim9ustAHIHsouhMvjsH2QgrOW5Ecpp6ZBRINKfhtG3hIGB9+TYAyieYlfDwmqfhPK6JuH3z2aiQy0IAbft1c11u2Hi+Wh6qwWziQPxYnDmi3g1x2nSPenVNbYYC7CzBetqIjiE99L8MCNeF5LMzEZyUT75tdrCUmcSkzNZmtvxyWZihCLD5QeU3msvgFHJs4ll35IyeOrOce0owPxm+iUzIBRC9bTcWQNSa95tzYOLOCUOcncmjnWnyxVejVxCxcqz4G+higlAjhQ9tNcLQCjVdYEI53DeITCfl2G+OIZdFhs+OPMXivBBfIkioIsLFOJgTvYP/a6aT9aUe31P3ryu+XK+S4JzhwONt2PyEC/QaXxGLz4+WAqSe9dot2NQrCBlpUpllPovA8BG8oyS/AU8OsypQ0T52lTimjgY3nTRiAjBjSGS3NjQZTvLX+DbtkzC7aGg==
    AUTHENTIK_SECRET_KEY: AgA57oKCZYVypsNFPf1k8GxjKXyF2uKi6rOXO+wLJ5PsTssV2nf+SFXtOCLpCVq366Sq8CpSaUErTpJKaOrJAAsUiYT31c8okLFIq+CnRyH84OYmHMGE3GRnjUF1vJO6n5D5gId4eXAXGs0QwAWDC37kDuEARyGyRnfZ87b/fJqw6y33GiWvoHsXRHj0cYyfrt0Gy3Hg5ZVk1Bs2A9fPO06/Jqa7317UnAwPVpDpBzZGc5aC6+w3gPe1193Bt2rTdr2K07vHZnnkyAogiv7QEvhrp2BFHNgsEcsIXBria4Al56mXs/KBwO/W+GiySqOsxXJtWUluI/n49mqGY3GQuFdk7+921x7PGYgGGA0U2pueK4J2gvJlLnHYOVo2EwSRx69l0EDYXqUcIszMF4sO7NGFOjzbJDsWHS9z3WrOA9X4sxHh6ROA8rTPwqtE/o7vu7bQ2rIyMdHib+oFE4zPa3MH5ayHD4l6Ha6axWBztF1nhM3bw3TIXSvySIgokJI0K1xlc7lRGF4ghc7YAI4Qt3QXmQQ27VBm8fVYRf15/yXQr+GqSJvrpDiLv8LRZtWe0TxXG+879HoAEhABDaWJt4FXkFLhMFPScGW8lXqDpaJsUnUzRxzw2gKrhBBHW7FNsSDSJ5WBWGHXBDjqdFsLB4cZu1RpexGwTP8WWNzjJ+cd/29rrFZRYs9vGaD9wDa9Frn09eBf5k6YklfjbfV41sHhDsLQT7m0fU8A/JdHwByr1Q==
  template:
    metadata:
      name: authentik-credentials
      namespace: authentik
