---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: authentik
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBPNfrzjchUhvIjltKYKR7v4xf1YzK7RYGWTFXB6sop+ezdwstcqs29QXKyO7d22qe4chv0c+rtda8QPnHYlwdkJslOoyIq4Aicu87QhNc6ONObTHWayG13XzvwjQDZ9yDkiuf+l/z00Du7n4p1B37JLv9U3y94MGcmKGdEVAwlBziw/GApJkgyrPYKx3ZGNpPBfGR0qoM1fiv5DjGEem9w3cNFnUkPd9DSOOvPG4ZtVQvrAH/jGqcMll2S2aTbGQOwazvKhkXHdEIV1yYJeDQhsjMNGoeaWagPb3T+gYdT51APO/cznXt1xsJ+Pd3YAWrqYb6Snz9eB1lfVc4+lz6GwAai9dGeHRNe2KLmzFumSI45sGgymqj9hqbRDRbkOpTutz8WXyHFYJtcUe2B4JosDsXZ+QfE9y405C/FdI2rYz64OOPhHBq6YsZZmn/2c6euGY7AOlwOBVxVryKtcfb/JOP2wvF8edpclozyEXd/NcGc9XLNliWk1EBiJf5MgR5trItysJ/7VFdtEGjwjIEHlxjgKwjxYF7/AH/EcAX5R8x2Zg3fL6+1AaEeX+x6MmXr0i8gijlleG5nxyu4NI+iGWRivQCMD6nefhOeYe6Jnj0ZOtwLLka3H46FadXiAFTQKy1WixdZ6UygdkotOK0lhHX7sczXtvL/Zgr02nV+omex1YTEMZL6A9xNftk0eTWql6w88yH4G1KXE9X7LpvXU/n3CDu/ZCK2yiXfWaKSeY3i+FyrwyWgE0c6BWez5OtzQV1E/gVhgA36trvXIoD1AFunSvXVDISYrGY1SfmonjjyQH+LykGddHFjLHaKtSK338ubX80ninfoMdW11QvsXBRBUw8y0opg7zZOqaUP6iVKNCb2aiLoPWv4QRWIhDk15sZi35cTXdY/2jhogfk0qYVPZB2mHCbv3SwOjUsvyk9XTXkIymiY
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: authentik
