---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: authentik
spec:
  encryptedData:
    TUNNEL_TOKEN: AgC/hUccd5AOdtmht/7r0ZHAA2PTpzpGEkgHAtdKj+/jQUBDlyjbCEKdJkd2CWVXRYIYfacaW41UNKCFpvoUKZ5c7Q+ma7vbk+QVMqZ+s3lKwZlJ/nOvAvfq5xTtCrXkhxPa5Ezg4A41PRTOPkfcJWDRSGyA8XVtcPaoz6jP+EwqyLjHurCDwX8ollk+lvgxdSMX3X66Fqm9yCGNc+Hz3eXdsbEAe8N9XsWweTuG5uHNbqg+lH0HmSlj+xR+qe4rXMcRgBkAip0jCxabMvZWtueNO7wcR7g5SAgaubOJc5A2Jn9STWiYsKckLTS1XgK93Q+3q9iwKsyOl9HDekgKV0JEETSVy2aq8hWyow1VciVRYZt3lbfxjWHkTKueKlBa+srgdnlX0AMwR0gdVgE8aFFhhA4PMut+cJysR34qE5oCxJB8ANKL/xHAdwuG5mPJVKLMu4RA7BuT/UGfuVOvSXKmQiEis+SPvoDNJO+d/Wx5p8yOfc0UDi/RRiaEmGMtUALsAEVt+9/ijNrdB95//lBNkvQxVidEL6uKWf5yhXh4MCkfWLuxPcM9NIhRNuOPI3NV/3/ttotA4lBRdR+2fyFLJd62euV7QTLcXPLBKeSRTjd8jZiAgH8LplVBwTutSex8BHQcRdHzmo2/OMhONk3UMJqwc7ljXfyUeLT672P3379qqftGpz0wnmrb3+6GeLatjgNq/bJwSKpq5ZtMeo5hgmoqNuXJ4oxeDcIwl6ePKpaQlEwqbmbW1rpYLx/eS/TqPDtyR5vZJ7dzJTThjEnE4BnawxY3eRx2rhmhsdA5yzN34TK9HWCiuVub7ekm0TjcuStsvb5YY4hb9mYrxEvLv8GUD4S02bBHgl5JZ9WbkwOQXlAnzMwI325Fkwf6OP3hVcyWP0lAwfjbn8XZSl/PyiTW34eZIzUfHJOsrzHLCNlIyjd6gPCe
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: authentik
