---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: authentik
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCgqf/eFTP6R7p9tidjvcPMQfMR1ti9yS976Bq59xD+igzI/7iiAm1oyJ6tME03vJMLGYVwkYBntJ6roF+fiIg/LtlqaZqVIAYFgBmdwrHizAw5q5zF9abGcW5jqZPMqhORiK9B4cyI+7DVc0x2kjZgkEN8ULukvo0J2kcbomLBNVl+aL8lCYrdZno7hjNPNwgJKIOQJFjlmyMla28lDvcIdbfUODG8J2aGL+zJWU1tHIOLVuXnrfxCrOEfiDksa6XwWdQC/crVzzo0CD5I0MUNOF3aOPJk2yP8WOPhHDuIbUhVo/g+S23FwoAHbDhdizvz39vDq0rsaS6oowg5EFNLVytJxhI7wgb+OpT/Fqb3ehhKsNyhcu1IQfeiHkmKxNoptM70+Y5HjZH0iZJS7RB1vysBcWVQdVFj650UalhN2NFc7CPV/6WwRxxRY9Fb2srG0x2LLXyrleueh4XfPIYqbzYAHOPG+PHXTnDf+DbJys7S53AZvzRwWrpT2HrRFV4u65tFQaaSYlfBDAhM2kR0YZIteRAqON+1YfdtiJvvbOkWxiFHe5kzUVKeiCpIz3T74YLYOfH8fxbdZlYyXih+cxtmvlW1xIpx7p9fhVVXzET49lPqFCP2csV1v4jZ92neVDCqn6k4sV1161ilQ1KF78DO9UWdtRrLYgYuaGm6U6yiWZwezTzvRHOirBH+1YG2FUeHvs5qGoPE9oDqrBTxckLWbNDSesxSQKbN2XWyRaJtD926+bDySfkZrLhoIA227BhVrW8OSh/ylvu95euqDMc8CPSTGVRmC35AUAqsBGeeV2QkRDgpoDS+BijbzlI8QdGz7VIsj5IH9IaYGiu0HB2gYH5Lqnco6EV6bIdlTStBQkQ9lXku3jnklXZ3YiKdtNtD6F4uJHTJD1sKdAtVvXwHRC8ZDW9DtooPvuwaFQbwyQGZUbh/
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: authentik
