---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgCNOHMyjqPfJywNTHcTwRV1KqGNcZTaVNMzkWXwGHkrul4DRyFS9cGlnAWMmKTLsk5lewe8PMjQ0Dx/2DSudgBLESfq0ung7OQgTA8nax1Zwxs+BNzqrAmvbZb+29UVU9k3DIwLRr4F8Pnk5pccOiwphjAJcRA/ngGB+mziTLMJwQ7lePpBCquGRzDXPgMuY/Ct4xxzxxK8gP6YXQSUFTlDUAqvRGQuTJDSMTnpMeDRzRO5Z/tvtPhubgbnn/xcOrNMXmU7WQxaZvIKWg7UWwGi+YCokmqIjBclv3EEyIAVPsQFfa2TUl0sZrz0czYr+93crRhvOO1Wu5jyEf+LvW+kDAEJEn3BzQ7e4g6rDxWiPPgS6rGZA5hY9xU7tl8Re+JilKc/queM7IjZU03YHwvNmeWavdcd7vHJFvvkF27dG+99PNP1tLNG2LjJ6PN8hTLBg3h3sYg/z9m1IfX4X0cnIaTEyKe0vbdwcPtofAlk426q7GN5wi7IQfK28n5GqWMoll8rllYzUFJf/pqY3yah14wbS/8ar62ExcJa7pySc27BRRV+U5FwvJ/YO+96jVlOmt6S77xCG66yX2YBZhX/2B7aqYneTAaqmJcc4RJF1BJ8O1G+55uO9p5DjHeTXEdznyRtk/SAjoCLGNWDuechpiJUd4f84J9q5aVPlZEN82B0oA0CL0Zhxa2Ao+/8fZeNFVz+WG1rSkRPeuabLf2f9Q/+
    AUTHENTIK_EMAIL__USERNAME: AgDDX6knddy34NiehZNEtnyCOSH0MBWBGtlWD/YpBjen0MFwlDfZen0rENa93anXlksKvzco93I0XojumvyMiHoQB26/a4a7/NyMFUmijEGo3m3tAT/rmGov5RzX8zNmzZpSqfixTc2tLh0SuDWuVO27ON+Q0pvfzJhtnE4FikS8GVtvVEKeSZ3r3r6WnY7Ltr9idMAW/TVhrsMGIB8EXqYvI4sk09fkyI0X+JwQVy9/9bVrTbunj058bNS25UO+yxSWhlT5htFcKGuc6tsiybB7EAm0PbJuICc3qObyWJdtuVhrntTtPsqQrIzhVr0aiNgbSI4VRljQInJ8PKkrIVj2eZ+LStKmHuraGdVLb3BYbVATk8hqvM5Bb8YkJ215owgoZdcRavaVk8LCYG72h+in2rsIFEAo6BNE8wbIJk1FN4asLf3bjjDwZPspi6Q3KJPsuoNxCCn0R3U9foJIimwbPTE4wk2bov65Vg9SPHZkqpEHPyrkyDy1RR4jrJKcgyNppDATFRexvowb/GG3Td3lVcAp+1gPNuEoJACHt6lfJGJtd1k9DFVVt7Au4Vm0oWk/7xuKPPFwbLPBAZ+N8PJwMflOXtjHyM2MkD4TItG7O+5E9JPQNteQ2CWz5vJoPfUQ/DgBiOx90AfK5JYeicKE+24vJEbLHMnqI5TgeBQK8mcVg56nglmyRXbK/AFaHV7rz5zXnuuy+M7SaGgOlGycR6BWM6xzYIsIKlX/fYan
  template:
    metadata:
      name: smtp-credentials
      namespace: authentik
