---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: monitoring
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAhQ0ypGnxiwwtRPcvMbSqVZGLwRDkh84SuZbMfX+Ujt8WAOxPg7Af/vAsKhNMFHhkGuF51wCwIowbMLiNdxz+1Fb6ICPnR7324YU4UtezQLskdmud1Hedgb366B2vDRgCgYiSXgMxShCEoxvcfSqWGTibg71/EeO0v/cohxP2Qo6fE7/BFN7+NW3w4YKjIDWhvyFEwrJ4IRzmsBpF6HbsBvkD2c81PVdIyYLsiM2hJ/n+CqcBnHjJ/rsdEW3+Qe/gHipyeOz1kRzMdbtWEL/GVNGBHURMtlzyousA5z7J7evoeqHzVs4WH4xNEeXpHM7RSdt1EKu18GMbIZ5aKSMXvSlMkDoCrvaSEzVYTMAQCkjXmJzzxyekLfMC46GbBYeiO3Ae5q+ZexpUmHM2w5DHcTdf+sOahU4h+WMzpsNow3z9tMnQAHQ0rllUmbPulPzWGfJTmsmY9nUQnxbHyGd9BZT+MGeCDJb2sjurS6KQ6yu0/2DvDRwa5+5M96ZdTAlUjJzKODnhILHmfskoncZJ8g6coyFKYtWi+OBTq6g4FtEKJFTqMGH0pRjMVbSjcM8KGWDhg1AQCHrsgdmijL8fxT6ZiGYpyeVHWdoUfxyMPLGhdwvu+nD8D2Vt29m0Q22TLEGSM5JDvP7ziq4Z6BsTrPo0wDf6a0Oq76ydp2Jl75g5pqb7oiEY40dQVok5Kkn45P4yqs4K27obnOzK7cfREWls249WelM9U510x6hs/9lnt/4bCATDnTKlZhS2yhQhZzXjLKv5WCbk1RFI5+UWL7jMAAjFm9rOaJ1hbHVcl3pyXlJmWrQCdFDaOdh8RMnibLaH+8luGgJ3oO0jxZ1+X/+8t6oT5V4DanMoegHGCjvOX81G7fuA8+ex3XX+ryteXl2UV22iD+CH8BOqsKsr6biPkDnKIRaADvKHyOyt1rwIpxGDdmURE
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: monitoring
