---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: monitoring
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB24h80LGUxuK6QWwSC6H2iJp/lMDhLugjFEsTA5daCI0Xx8I6w1o+7MWlgjZA9ljPBF1EDi7cB2BBXezGAxb9YaDPVJbgW+VB2vW1Tv7gTwqxdSOdh7EnwdOGj6NtHdqpmo0soRpkTTYWxiLIP1B+Yk7ExufKn888SFkcfEsLJGu4+hrpFaSOwGAPypyxEn4zXGoOAf/N8kLc5cgjyLq0wOskbwTeMZiB3kZ/7f/DNWpVovRLVAFrRBInmOYgT5+dDQ7W6p5qVYxi1uyAyG9qBi7czw1woYy1D+NCLiEEcPXkQ+BJa8PcygpzUNyk01pr3ijFmbaqiBsEwqPacHGszjyuF3Xav7KWmiZ1qCDZbPX32VGXYUvpMSiS/aRC+40BaG7R8KGlnezaMmAMbebd3bewi8RE9QpMh67+xFwe85zishv1HyOV/inydDU3hJ1PVHFqwoQ6QyOjDKSN37dxU68oXM6qm4N8P7lXg5F/lxnZKdNEBTdz3wsAhcEMz/zcgSyX7gXEUHw95UJvZjxCuyqUr8as5DVn7/ivKJl6hf2EEVAuPHqBF4OySu9Ij0WOQ5YltiziD+J/MsGV1LYmNF5DetWjZosfSgtv3wIF42ynVW/o6SEprqG1gc2qU1f7uJbNDjJkUgwBihABdtrBXPVfVyUXg9W0NT7b5/i+RMXvSL+Oiidpd+BtysjV6K/Wl3GhgjStKDFK+StJOsJiHtC3jJGwwuWSTiT2qYylPBo6k4twpNZ2HLIVmJ7BBmff0ePzNmDRpOB6zKw+P549T4URcRxY7dWc0phw3yUSn01+yEF08jeSuZkhZWCkf/1yGpNA8fHQpH/hTHs87sEOcaIO2zjh6ajg/v4WbWt+fM1tdYDMeUxv8QbDtrYRTvSIAZwgJfAkYl8In454LV4DrAeqqtLHCp2os9oADLTJvaefQauuHnhlf
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: monitoring
