---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBZWV371yE7l18Quny39pXH/prXDt9NvMHE0T/I+SooxkAx8//axQOqaPkNGGx0+POhWSMySsdqMPkmabSFn3ARNHgcGWzD9cB+TG6pxfdFKVDRsh7LCMuNVAYDRmWB0UNyenm+VSxc6c+7+WOPUMb1BWyhJe6ac6s61+EAT/Lvs60Szp7YhytlnT8fAFlZ3yTEkYy/O2jzJzT0hG4Ko89qAKo3ezTWOrPCg+4X+47E/zIzmbgD9jaZOQy5cQsWY67V15kCaU3bIC+PdiMynF/NZiCujoQnyK34qusCNN//tk3TlmdLhyM5fSlJ0G/2L3CxugIB08bFb2mJjU0XA4JXZ9rReo61bdab2ZFvq7Y8M8f+/Fr13ZcGfcu9nL5DeopYJ/07zp1a4o5JIvdF6HzMoWwIkYvw0EcDzwE9DsxFdClEJVJ2hyNUB0h8A6jG5OSwciF6O5xsGNVKOzpY7T+6q0MViHA/FkkOVtP2rjVxegB5Jhehte4TmrM65FujouhKZTp+djDJdyZf9DfUdPt5IrVeexIfP9TLGrQcrP6Wh2lb6HVmupyajav4cHeJePTkJuGyKBbIYyq9dt3kQUv7wWdq5LBJA4T9/wpU3mXnypbsyG75HMkuRPw3B6HxadTQxziHu00Da2E3dgoPxNEKyTTGcbEZ4/A8QxGP9gIEceEauOk0k+4ZWQqIolcJtkh5c5pC1OBGGW7iSWTmqrRsR24CzRMk1OGXtjePjkxMZA==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgDGr7a5peWwmsH5SDmEVqfnzniND1qNjRtN7D094r88Rm9eLheuiX2NOgb1SmeY6vkM4Q74Cub4gAji9NJNLcIto9SQF9bZh8zJeyGUK6yf/jPbX7ERVqhiCDsyFcg7og7hPz/QfOVUh648qXYpPGuKe6RZr8M2aCAytokKJvkLvLXdLirca/eAmVwYvhoWEb/jVGOz9MDZP2Fd7c//IeGisRlhVH4a/ruoVXWyZFaPq6PJQ3fnPDr+FKsk9gR131npIYODj2exFskPsg1ddJpeDErcVgJnuqLmq3EUJ8wB+NDIyfSma/9uerTlSlM0R60q/JhC/f2bRFP2T8SXCwNmCg0Vhvf4hycUjOE2qtzB+PqCIRUAyxLr8+pqAbxGMWeHThy/W007t+0AmtAercL8X6qDx7D06sj1I7u+lKsfAK7O8bCPlNNuYvX58R1JGV0D4BX3MaHeVooVP/rs07FUSe1tkG+aauF0BLSoGfRS2IvNI9lbRt+D5u3XHUgC2svn4NfkYchQPuJxI8wGhj/kUrflnI+SvdXR6HsjHdCT2zkQo9t8pE6kzc0PNG9hrPRabOOAQoZgmTyBvP2HGO4fMj6BAOqmhqfFhhjAD3+stWJHbbGkLqWAfpQxd1Rh4Wf8bTkCbAkL1LCZTdQg28DQOPb0gYpl4PbGNtdrJsO2yKEooGhEy3K4rf1U3AL4EZwaX2Su6DB+d88Gi/m+1p3jR1i8z25STDEN0GqTuUne2A==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
