---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava
  namespace: monitoring
spec:
  encryptedData:
    STRAVA_CLIENT_SECRET: AgCKr9w8XpMx17+WR/jJRLg1uvRq/OzyqCMhohb8woRFr0qCE+JCbbmPaNmQg4b+souRecz9Jk5pi9C90T4hyxJT/jA2bA/lsNLySc69Okb55nRWcDhZ6vhNXQ2CScHKzNvcf7TjPdGp1NEXRVgLYIefjSAs6Zn+DXzLR6knxiGKpEI4TJjMa3Rd2ZolWtQlqqM3/ItT34iQf/8B+PWN+B4JHQza2QtrUJmXm3OC2bPbZtIWc5go7v8UnhkDN4xRX6n1bDPLMaL3AUNAHa9KUN3lwtO1aSM7IZxWxKB2gM78uZB7CkN0e2zL4HQgoLyDuGa0G6XIP6Dp7BTyJOwkllSHrMZpb4Xv/m1HVu0VB0CcQM1l/Ynj6kp6BAThIYr79uuOSk6OEu/frnDQBzSX9XV932gnYXiBiClcL0KWFbL/q+Eip3jGRtrfFMejtO+sC2cTEjwmD1baC6asiVE0mGn82crNzVe5hCN6yRqEE+vHxNOLsir36FNOMNVrpkONOcrkI7ylQQjxgRPLG4o3ZJdcK9j53o+wYoo3m0g7UCJm8UdoceQtTjMB8HVmatWFhNXqaLlNCNWx2N6eZkHEog+/DNUx+PLwxyzmTv7AwNYTCCTN/lNZoc0kQUEzYCAU45RLOUxA31MnmDe+sXuNOgvaxmcvqnWaJfKr0BViElsXte+W+SA0j8Xv86x/X1cDP1d+3/V7qtGFdAKXuc2pS0u6KL+gZ2rgSJ26FFtOdqdHlxOcAvxCCBln
    STRAVA_REFRESH_TOKEN: AgC5KYDwUOlMdeZ662P6q9j+wUxEF8TahM0anyuB3SwlVpjOpQEUf8vCqLsPVx8xY0pw3/lshfK7k5ibrEkJD5M9V8ObHATA66zSr7k/2KxA3u9qJauQpIKGehN7mPV+0km/puaNFngUB1btz2COSeXipI4EluFsaEiUac1Vu/HAnIMOp/f+GVaI7QZIkoqs3XmMsIpu6JNBSp8chBG3dmNLv/dURD9KZUgSRQsjP7oQbxfQGMVq27FgX3qXjOdL44vFJINHbxuVx5cg5oqsu+iBOdejBwB8iKqhj+Iyx6ie7Kg9P1Qh3tSqkmgGi4Hp68/VcQeYuwobmzOvb8E2LDpkZUwY7Q86Xolcf+JhlldJRGSFVpJ3TSV6nJmD7I28Ki4z+rQOwOozz5Dfn3K4e14Fr8neZ2TQVIXZ9lN5EdciPVKCwY9UiUJJwe/POPJlurOutNLA0SVjwCz7qDeNTg2QflWtVbh+lwtC0f63yYMgwFTnmvvesMvQtT0aF63Jn2W2e30h70IP503s/0zjNwSJvqIzceX8PUnTvkI5E4jHBwSPPlkM8PP6UVqh9Ma/+tCUtZY1tibFeBbF0vKazKy8LdPuoneqHeQwK8TKBbMP0iCLU8Dy2A7yZSHOrNq9YGA3VUFZa5tUHtcvhF0lg2dDlWygZUFRLl5GwuqWT5czMZo0Hq3nbO8qMQR1oDRikLEaBC/DzYkSqKcEcNXC9iQ0P8uTyQOApmkqkoOMaczLi4carI4UWKm7
  template:
    metadata:
      name: grafana-strava
      namespace: monitoring
