---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava
  namespace: monitoring
spec:
  encryptedData:
    STRAVA_CLIENT_SECRET: AgCl56Z4xgmBNSQH8Wx7iN6iFhwcSOboSP/ml6JNeYIiVsSAxreFsa3X/4U0HT3H2PEMlzm7IpGSLapc5sE3kL3IHaFhWV/VoGbf3NxxkjNFiq+vJv19UVPfSbm+v5QrUbKCrrtqF7DvU76bwqY/xz6KRGGPy7JTmxs2HKj/8zZXESEbYG/HLO7EQ5A6DhoJARRV54tX1/D1Qt6Ei89rrDTlFrZty98i1nAi9DQ0dznJBriBXazA2Hrb7BCtj8TG73DhJz8PxfDjLC+L+1PxKM/2GhPwPRZQXgCilG2bAP0d9BmW0TISu/iBjyP3WM5I0770SfahENkcZQcBeIdDQMW/EKkGKgobs15sqQ3OQQktS1H/ADUyP9gg49iCirsR/r/w9ETdbFVqY2Eg3TxZ6fJfevBw9KM9WXl+uEVqxMJd9UHeofUnDmrzhxUy5RaX+fGNvrAVXXoiakjx5aHaf2/lK0mTCyfx1WeXuL6iGSudGn3xeH3LsWlcxxFSJ8a1nQxD74rZIpLlPaqVIOJgprl3ur3xkWpCYe/gNa9JcsYUNKXEoOBB6mpVPLTvhqR4+YR0oyd/GaWMY+OsqR2u2whEWE9Fhn+YpaBfJUYUWyKQYR1rF1Ysf/NsjUPDHpwBswgzMPEoYsPETsDzanZZ88tHMh5UGO7Rffs0Jf+j4r3G3iTepEK5HyxfCBu48/gOkUjH4VggwbndhHTDrwaTRududkRq8c96TkkvOZ9UZgDQqwghxFOwZD8F
    STRAVA_REFRESH_TOKEN: AgA2nlYqbKnJ8Vcv+laFxt1S4Nb0JdjI6YdilqUjMItrczSf0zNl8vRX8phrhQCgu6pOfzv537VBn9xiYJ07BM1gdpD2d0SLppN3Btbj5zxv5oX59hyM2WT9ZO0kw33ZJ/E6Awzk5p149+GSm3o//LIAd1oq3zq3zBpMMKLNBMAeC/v466c/PNkrLqfyHcBW8o8+7FZfQLQH6+wQ0eNZigaaJqx/7a59CLdnmuHpnDih18a0OIopbq/GkKWgi0X8MtjOkZOUjhy8v7/mPX56yTtaIslSFMgVvBckkhgAooOsfFix+DbW63VhEHtOGiTDCRXKgVpNYLri2ULXMWMjiXsw/s1tI/7hwOhiRIP8cdHPPwi7CR0pQ48BNojVbZ33rqMwaGCTsetOdPDBjINaM8WEBN58skw05VzobxCjPJBY+Fi8uut3W2WuDANLPalA69nkwHONlAqXC5JZRqfGx8cJJCWvHrNFUaTizY3OXzZBR04zqe4SZIVLrvM2uRj5EhRojHa+OGUZVUjlYgs3qp3ZvN1A7TwexOsK61Q19v4mB9sdhpMKG3+16awPqUaPoWTTvn6gi9ddxYb2huvipTgFlrpbyB33U+v+EUAp8ue4QW3ly2Ne5Lr/RETzp/h+HJeeYLNe1HsgpsrmOXNvXteW44bwKr3WdJ9xvaxlJMonXBmla/V3rU0hRkml0ftbSWwUZFRxoLW0Sg084bp5RXiNlJjg0Isl8paVmLZGITyKXk/deQF9R/pk
  template:
    metadata:
      name: grafana-strava
      namespace: monitoring
