---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava-2
  namespace: monitoring
spec:
  encryptedData:
    STRAVA2_CLIENT_SECRET: AgC2JxlOvZY+JlQLFZ892oI447i36ord2y+CwuP3HUF+Csc9m3Ixqhvt2pCxNYub6mJT7b1kd4Nzm/nxK+7h/gYPF39tzRV9cnTWcHQBGNPW22tRe//DhurhzI7rx0qNaSS2NCxCQnG1HM3J9SoSSTeEAc6JqfBxDsOAGgoHCl9I/WSqiHp49C37p6R3KBaJPPftgrCaciqxoMLsFvjVyTTT8oF2wgRQxXHQnNG4mVlF/sElTTaPkNBlpcwRKghPnqS19V6ZtC/GjKtiwqsJR61DZIULC0I9uwNwn8OIqdVo5Tr0lml8ZGetlI5Whkai9A1odr5vTE3e2r3Y/+wdicwodJXi6WotGDzifqgNZ/AvKyjiJORjpVnTaYK2Up0v/kiNz+ZETUxCScWIjM4jTwxXOfvR2PBsKoRKEx6NtKxRcqduxmwH6o+3GtNXHHRsmud8oTt9Oqfjg9UvrPCF1rSV4jHQGK5MAZksfiBti6WNiLR7f5cnwvs0/jIg9o4+1dUmOS3WEm+JIlulx2IPPWfWPIzDkPLaNZnYZPnxo8VE6qOlc9bTknqKkEgJqL/ZrAtsfrFWLupC08Gn9eLstFKPBIV8ZMsjPAXvs3fXt7W3MzK6ZH9KiBD+QIkz/gnqk+SFOWQZg1Y2+ieBldXFlcm4Fmb1Yu4IHI6/otrfeppbJl9+sUEDBetlwnSRvglRZGc42tEjF6CGATD4mMRiApXZo4CqKQW7fyPWBfNhBNhbY3DI/PrXRM12
    STRAVA2_REFRESH_TOKEN: AgCrkXoSUo3gRCnC12+xX3Ij8zNNNpWZYK5yLnobm1V0gRJkFGKs6hUnKfisUEyDgglcR42novecdR/N4j8WN5J4Jg7Q5mqD4NQdTfFT3Hq3CbFqteMiQ31LgKvXZBCxBkdOucDL9Sy55KyfyY0Pq7Mh1SeDhvGW0vs4DMr7AFIOmfysXJNc5wPPLvpoMitOH6TgxoHpFI/HTT6N1ROuF3YU7A7Vp4ec7oi33afhPaTTyTOzUewMxpyx7D+QuuXH/7f2yY/lSp+8HfQ/t463Iv0ah2asGImSzVDaLbTyEBmhZKioGMJwE5ICYztaD4pvQaofqhQHB20oJUWIwCII7yr1fdd553r/Do384VU8S8wtVPmdpg7fmKzTFmh+IinsB7Q83RV3Yde7qP6tJuhWRXXdNdxnt7fv15OEdENEIgA7MN6Amol59tGtbZcNh8iHkR64dsKOwJibQ1jVhahMXxHegin7PJSmT6OtiGs9JUvqGLpyiOcWUK5U3rOPWAWI/KFG3Aa88fwES82CzcRQkynj9tIcowITSAu1A/TysrpCp+Kk5oTjAshcu35Vd3bcVkDUGDXh9LVVoEFifjsEwZjQHISTmymfFzLxa4FjplX0B9z5n/g1xuuiN/oqc8WEeQ9vqDhri9cf4g7Pe0GbK67WXzy5IEithZ3YC85QiY5OjBs4gW65d4VqAaMJmsPlDvzyD/7lc5Co0c/Q0LgKKeCep1n7KSOlYXiogs3/TuDsDm7nr267h/IB
  template:
    metadata:
      name: grafana-strava-2
      namespace: monitoring
