---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava
  namespace: monitoring
spec:
  encryptedData:
    STRAVA_CLIENT_SECRET: AgAFxTNsIBpxnMRzXO68/nLyVce+N0hwjMSSsgn6IUgQ4wnHjk2ks2m1Fa0jQYVIDwYT1Lv/1xJq3QplX7ax9jIjSBewkwM/m5q5/E1Jk6+ous05c/OpYIR0WBC8HoVHc/wVjHs274Vg6XSkJy9nmD+uC83+L+odxx6KFR2V402bWnBl/COEvItS6olXB2wz/byWaPOuIo86pZNNSWaUIdeLk3nA35JCIygjbDnDbB6TlPhy225PkedmAoTxIxXelzp3cIvu9HbyyaZ3giQPtzaEhUez5fsRwVKCtXeAhEyslxD5xWibiAtmBOFAFE9ba7F6A0w5OZ2uIjoA+NVooD0eUW4wQUYgViaoJkxLnAXush+8t8h8xXZJYI0GabVPYpcbWPA0ZTpZVN+xqOIgI8Fea20T9s/HAcVxsPDT8z0kfNFAwle31dYeMMI6lXWgfNni54vxqShTwRp/mKBM0DLlX1WBFIbTmb/R5qrGN/pa9Bkf5Ucpqfqs9nJSN7OUXEPwOKNlK4anqzT49Q45V3mwqrVUpe1Oehi6x22wnrNs6wKGOXLNLHPO3cXoWQMjPjXKA2y5I/VBfcHtbBrMcmgv4mta+dgyRcEwYgzSAHExA8zMxkuV7nN49GP/vqqc1xLKFXP4z75rdBsrFA8kvcqj8STo44wFvcVaSIrhfaYmT7nQ8q1AqN+wlqrNhVQ4m58IdTZeTFZgtDPr1vHL4bCNz7gGSyaJhhH/BK3MnK8rDqjd4jdvxCrU
    STRAVA_REFRESH_TOKEN: AgDBHbGCgpdaxHXARGRHJNxvV832wt6q5QIXLs6BYzYbUyAPWUDD23tTIDLlCHnaMkaT8vTX6to1lO1J6LY1iRN6qowe/FwVaempM2BCtNjdrNXR9SYsgwqJn6gDEJR+E54CX9KLqbp38E9FqThM9IF5zla5QjuM7m3qNjBJ8tz5WZR2BFVFWrdKPpDB9cFUl4+riBV2bRPXOFwuGAPsylJFptVZryTQ2f9aYsrEzk8/tMLZx7uOQolr8UlEWLSZX9aYT7/YDpLR8tc8Gio7pmHimRvfE+dr5ijEgjuKa+5jq8x6t8EyKONMRz0cWBS5PO3o90uN6Koh2B6biv7lzwlQ1lMYc70nkRSWZFigfAk0yhu6ZxTLELZRWlF8pD6CTb7D2OiS/BEaf0y6GxwIxP+j6HGY2HcG9uCIBxO4h1gBJML9pjRz4Y3zC481ioBMX1CyuDRPsGyBMToSmBU3Gf2vaiB9s/7gmLaHkl4SC7JGcOVU+pv4DDrvVU48xeYFSvjzyqfM4jJohrGnyrJO9ISabG2y0gDQa0jACD1jOEeDqzpDSl62BXtBWnpOgpv07d5KzBeXkEJLX1526AEN2Q5gXkUNxtaYO+pCCK/k13mwb6BJ5aWxmNkSHnJo7A/a+1nL7zE+7Iw4MNYeXhf5Q0hfsd1b0Eqz1L3VSq+5Bn12HTSfLg+OSglDBFaDdv6cGslfkVTatnhmLre6WkBAfBrt6j0ualveX2EPAFfIFtXByio4zfPHaXcm
  template:
    metadata:
      name: grafana-strava
      namespace: monitoring
