---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava-2
  namespace: monitoring
spec:
  encryptedData:
    STRAVA2_CLIENT_SECRET: AgCnI2S9qry5T4oOhTC0s8QYccyR2rWvljtg9jLyNrOuE19BW9KbjiSHosjjOTIzASB8SB2PrdTcsLt3G14vWay1GD67TZmh4gYMjVq3LnZTAKBqU81EUGufLf0JXb1w5BTo7NyPUqf0Ur1dB+e876ldKDu4QfeCbeEZ9tFhm16LC+450GsiuwUUrfIwITCFcr967juJ5jjl1BawB/CE86EUkYiyo8sIMcXRTkhO5qLgA1LsaFY8U0EFnQiB786/M0zLuMWnWDHjuZIdJbNdiFdEKVbv7fahgU6uMVypsdslHh/71p+jyGb9YSZyZPiZWSE0mm0nluxJ9yR9CjIuoOwtYqHfJT4Afg7RFK3LfMUc4g4ziHCEamJTCGBiZKT+Whixod/B+IdmcHg4DFsTi6pptK1eJWnsDFpX3rAgaaH2g7ZxdZugtOefhsO23Xdbj7bkcruU0C4ihOx5TtJZGD0RF/GwShiJuaU/I6ERge6xxHp6hHAJyFJMhldFIUZ2hSHb/BXr83s12TrlCwyHtaKCP3WTyVikeYM2ae9PBmClNSk5FIiaRvn4qDWgcydZXk9osdDIn1kJo6yW+uD2H+M8NUrHzZfEctuwnUxrvHpW+mrv4y4/ZNPVv562TYbovSXekU4pbyEHMPGG5nKM716NjFdwnwRTjLtt3DNs91tp0W8r86hM8Xqw2cFLLgHPrfajSx7RL2egMyW2GpkE08CWfgXJlmisPTVhT7y/1v0snuVkflt3niHF
    STRAVA2_REFRESH_TOKEN: AgCbO4IUOiNx0GeaDfZqrbNOiak5BaxmUWofEFNRE2zQb4VsNBbDGuup2thnW0SzqLwQahvc/Ao8oS+rFlVRQxr3zNcmgFnocZpGEEAzaBEK2NiZoOKV/roVOIlb1c5/s4BKJNgyYnHUMoRZoV1f//t/tUaYW5f7bL3InJGv4cM/e54prSKWvFye4o8mrg5OFtlqHb80ww7MmjfzOJKay1398S8RL4TaC5QHuF7hgzekJOBXJEmwh5oGcuGHYZtHvZXtbCIIm2V2X2SQX4YTZTZKVQqHMd6NuiAq2xxU9W5gVHORbzFVc615x4KT3TedQTdzDrxhMQhqain4/R+eWp9nEGIzt99njssG3eHUJesax4GZaaixApWkaXats1Lo9gEFZXg5DsTmGYxgTJmx+8ZjvNtRc5enqFlfzrD0YSrTGmAqqlbmdib5XOFlLWoL0M+sUtpNauLpFFFsRCM0JaJQFBlp3UCqFHDwMecmrl8mhr1MwDF8YzbUoYehr1XtVr1lK/7Cd1S3VbwXpH33AoaJaV2vAqppNNatMyyX1cJlgNtIFp3fVOi0GAn//vAkzDav7Rjs039ydaEYrt3d7DgMBtDutwy1HmmJ9NSwqkQ9JJOMm/Azra7GPAiiz3v0h+XHqBTkePqW0XmY5P+6Oxy9nVXd9dz8SP7coPz3RKtdRucB+mH6iA6PjctSgKSR3GgQN8CVDz7BjZVjm7+TOInqqoE9n8h3wlsBaUoo4nbPOkar/r4wP/OZ
  template:
    metadata:
      name: grafana-strava-2
      namespace: monitoring
