---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-strava-2
  namespace: monitoring
spec:
  encryptedData:
    STRAVA2_CLIENT_SECRET: AgC/0N69TLQKfbLbHxvEk7PRquIA8I7zDW4rgssMmiaesDyKlTfg8pX655KJgrs1xk/3fonFo4iVWBl0dsVTObL010HnAfLKuez0Jjug52YpKgPf2/mFq7e0uobiLeFgVXbXCxnN36klAvQvjwmu1Joxe4P3UGAz9/Tl1gky/dmdsJC1byPbdiUdZrCYU7/W9KyvWvlRFK8aIk84N87IbfkMLptZNXrYfCQ5G9S4kRMJRrk6Rc207TQfIrL64m9782ZM+nQfhBzrsjw2jlR7AMPqn3OeqFhv+yVcqYev/CKTa2+FEkLsNAe7DELPKm3rZmiSZMn9qVRFQx08Xgm12IQUt6t1A6TFMBBqh7zaiFK6qwn+4SSBLYeCb+4IpTozBzw3lLrKJJ0T16gqxZ6t0MWm9XpxY03YTup7UauSSNXBGv6iHznIm4LDgPgO1baF+f0nzlrXHiAcPJlx3tlTZ9Kn5xlIPTL9EH26oZ3DkjjcmMERU9joL/QykOqBdykomoLlwJHuOlly++VlBvr98Wpy7OZtJ6VwefbFYu8+mbuAbjcpG1wc1NT5A+PZeHlpoV8HjfalKmptcbdXt3O4uYI0Ro3+GJmS8TtRjn+cl6wyRHiXHMZ+IhohGyDF7R/BF9XdBqnpQJScIY0pizqTYK1ID1MTywwQQKFnpC5tMgBYR3XwWztgyWrsIRjecwjc/24q4iOeqcF+ecZzpoUWfQ/5I9x9Hued0PBcisYmY/ugXqXFCS9+qUlq
    STRAVA2_REFRESH_TOKEN: AgCYWQfXFVnBsJKya5cu1BjvH7JdFK613eJquyTXsT6uThjUwZbky1AgFnwncFei9WhhDkQEASoo4I0eordmnCeG3r2x8d3VXxJEVXa1fb9ypFpPsoMtQ5aID6dJUcoVMVh7GbZaSZmnZ9MjJrIc55NhMHhbCrZmCWCyKZ7IdmVtS1tAAoKav91ipR/YNWaCigcmmxkcDVsucpkbDWR/4XcD9OErTreIigMd7DnY+E3FZeAwgKcjNejxm38ERKxlfdcHBhdjuoLj7lxljC0tufQ5/+1sVBOJJ7+UmHx4OUo+SGoP9li9j4tBcLuktrUcr4NR07850TfyPIWLpSmRZzuYccdrGlArw1KSuK4kSE1FIuX9E8BcV+xDlxCnkIp2+Mqlr5kBA3kmMePigNwnQA0ls0NerQRXR0hAYcI8vQqtzb72qOU5ErGqxpeFKIiBbKgS1BW+TGtabQCy9Uf/tug9WcHLn2q5F4ppqcnxeNFT38P3BJHjmxuX+p51bLSmWMDKBsQaEcYA0jR6aXK65NexGBE93B1+UEJtRhAwEdYqNbVeDJzxugMuG68Hn5QxwC4F3/TjjO14rCb0agKUqcvvHfoQgWvSwdGXn1DqtbDx/46CYPJHV5Mog+QU8AWlyk1NfZaX7XdQkOKpAuF72VBF7ejGC02eDnMu2DRfQKrL61UzrKJqxfLVKzMVv5Wf5kvAIxTUk26+Ywrz9mc/llIzRb5001/3Ojl/jcU4flrrVDBWvWFx2iPb
  template:
    metadata:
      name: grafana-strava-2
      namespace: monitoring
