---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgALe+m/rYf/uvAd4jxaRFQPW+FUbFX9RrBrDTiup643PIICduTXT7HDcKvhcJwGC8i4WgIIGkMxiEOYDVWiHBK/+pS17j1h3e9v00HMB8te24oRIyad7qKp4BMd6A4He39lovF/OZtgCkpBXg9Mubf/zFRPMOH36KW2RD22fHgwdVU+u8fHPntx2owRn9Rs+FvgK492d8XTuCGJSRwY+OdUN1iqPypaxYuIKVfd+h3/D6QguA1020G2L6tAGaeckNgc5YGwlAOxQhkClc496wQ07VA8gJ1bf3fD4NWGV6eFvnSNqTnlQqAiViXNuFmz1/RmPU93wLwxOgI0Q3twPkab2DjFhgKJZjHvwlj+eToZCXHmNmSNlIjJwqMDP4bE16080rfxhgpRPKRvYNzm1l8RM6VNaZYv/5e63LsKckNc2pGcjjFBxll2fuuekllfT2O0x/BezfJILnfI+B5oNYYYelsJ2/gS+wrxsdE/QDBLoRtVHZJlqiwhb9ou2gtACDoMuD8Lxslgjnc7Ls14OMCafoCbJTXULxBwWxwcjmvRPOVLP+mdFQUM9zevMd8hbH8lEH0KR8nYtOZtWxd/4o3YRTY4gei9lKoFdeegaiPJr9rIFuYX/aq01K4AWqo1MxcxLYqwr1iyqeBZgWONNrulkqjqmj9gzbE+XNmJEEco6TbBMOeGnic4oZ4BjGAwS0RwWs5JuY6pVtFXPUEGdRoPTzHrigeWY1rd641z2c2fWw==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgA9Nb1BQt/R634ZqfroxGzPCa1V5F/5Im0Y7W6D7o1kAD8ve/fQ9wBwEMA24doChqpAMWV0S31aXVZlINyACnXWbUKY2lkk3StsLC8/VZ00Sp8m2P7uaAL/+3Cf03Xrckko+oK2s7RemhTAtG+ed+voaQEuyVFzg/hzFSUbSFjZ+Vh8D71b9DnwvLJZerGyMKCS9zuxgUS/UTVmfbqyE1f0HB+4Pn3U6jeVcLqz9h5xsKQSMBhFzdSU0M7vri7Gf1srKd/CrDf/YnYhybJ1dJ0fdhL7asLSbOVyKbp7OeokuRPYcHSLGllRBwt4IpLCaNH9L4JW5ca4o/ddfr+9cbQEyhFwXVwmOzPa1rEnvVN0JSdnhoxDdC3xAzv2CbMWDjcD3erFCtyJgoUHNiIUVfAV9y+PjZhYtm2OySbc4h4e+mb9gtSAsTmTsQnyMQSO4TYhKVa0QBSBeNZIUmXa9IrlrXWOGR5AOeq7kXH+PPWdapgi5MDQpZYwWkGSZXs9FwQLNku+yvzRkg4k8uo8DH3ZWOvx+REbLwcsReEPMHATPBa+okmKcATsD2SJqoeL1JETVqgpzFsjbWnN/qv4V5LPsDwGpTYczOiwOk82ghus2WhYaTeH9ODwmvBKOVOp1Lp9ujaowIU9fdMKJlQzLrREP87B30dmtoJGkkSF3Upx6xIfuLONOSVCXK9wSSbQtnJ6BCAwI4l8h2Th00L7sjv5UiLCm0Hjm4BgtiN21Ph+Vg==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
