---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgALMJ53pasq+T1Dgs/YE+uxJRV18L4N7Z416tQF3WdpLO/rFn5P5+qTUCYp6olK21sr4vwBjHVyTh/9DWTTPo8DrZ0dfbANO3f5YCtPDT8+1sjLFkxH7fukwzzfst5ZmbruFg3LXPfBo1veNbYYxvG4biX8yw0lQAECvvGzBPj6/Jwx20n314OrPkzuPBo8NMRIfagR3Dsy1/66F7gmBfuzXS+6aEoxWKeMNy2xSoox0rvqhoGofaep5bLqJ6LQpgVE1tQ+AtnWq4k5swiYBwzabB0U8X1Ry/kgAvh0THIuqOE8CFUWrem7E+P2LySCsdf81tz+2RACtPycuTdhbiE+MJpTbA1OA6/aX788OlslKPGKteB+Nt1ole8MVrBMPWGaCvtjWP7ikxrERZFGIUV0yWWf6yszN+pGcSJvLHFHt8U7rK8rHve4Av0BHHtgpkhHtllGacK5wJ9qAd1vfXqir9SJZNUWxXPD6gBCUtGg8RYfTJRZ67sPoJN8X71X0Y2vb2Q8a5FRkCLf2Dl6s9mu+Xxeb6aJgUqxSGYsotm+lDTGAVX0A+V/T/TqMgtGZn6+XmiGBP2rJ08igVvPXl63D/pPj7DPzRkFxcwriNAHnhTuQfZvj8cCDKyWTDbHhO1LgMvF8IqaovsXSD4Gxs4Xefny0xqb4twbfMx3aeqW6uiaTAFUSZ5pdzEquG/Ns1Js5ZYo28Fwx2sRnnbBl+GVhy+LhFX7dQD63crBRLPGSA==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgA2RW/raWHdAtk3J+w0NZawQnj3bQ+3chn7T6JyTTB4CUTqxP9NwdsK91NMSoAksmEItfUpRWxclrDsEh81OqWd5lXx5wo+KZF8KfoumVbaSBI8D65StCWJvqY9GCYAjgM0mMI6P2jcPvn5qCIJK/tUcsOYRnYnt72pu0bItGNHLRHkJvasZVnCjcRGt3nW1oow3XRz96Cn0m1q2XhT14e5bp8hW9KPgp/VZl/2f6F9/IluwWDKosHZGm+qMDo2DuwehpOy2mmJixmeJFWweIScJ8S2VyNIkBizRxGd4kheXMQB1NOOwZeE1d51/pU+eXQSaM7Sp98BH/ghyutnZNR1JF+qXTz6BPu40MbLJVGPxqn5LTelWO1RF17VV5gxWCsMikYvVlC5UySRJr3eRnrnFbh6HmcywLS5uTdif3SBByIZ59blbnsKYTTAUlGPw5VoO78ehOsYmdWH0hyFQ+2VeOq38dA6+dRS95bboNJ7DTnW/psxuiJnHNjSJ52lMPRJaKeG5Ubt4z5I0+mFCC+z0rQvMDzS65cxcYI0Bu5voOhytYwWj422ceoEEl0RWIizCG9RRYiC/W7uWLSylpvsnID154sos+NPPGh/NhOGMKQ4B0z64dgH0ALRx0VyP0tjICMidN6y/XQVG7/OGnMKqzBFISXfteID6t3/SVxL5DsTcvwElelI14kAuzJ8glrBD5WecrkISwpwtQGUBwjBpZkSxxjC/snv1X9XYJ8hpA==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
