---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    dex.authentik.clientID: AgACk3C8x2mkt+aypzocwk1sKjDDnN/rw672X01axPmnzv9fJGVuPLnZ/zYHQkRzZHg/eGD1tkPyo0Co3MhnCyI9mZG4U6VKVbmDEL7Hb76XfCsnz0JqamJFgz+t07A5HhSCNzxtUxfn/43IMXUDkyf5VpSGl85aHFlB+PAASn1veuAuyiB4NbSK+68a6FBGShw58aqDdHNzpdDyWdXiTgDThjAboUG+9OSmkhc6Bg0DaXIM2MBQaWqvnwCJXYlKeQY+GBMAgZkkLXubeQq1hlfre1GVfa07sCrX0gmovj+oOGbkmCzWHwgYrl8gy0xC9DnVRzIb0oKbqbAwyjbp/hSF1wQM3w2z5HRMtNdgFipOGtiFAQwEWP8TsvwRkebodpzh9hCX2U1Kt7/SUfJbtXg9SrhEbxHh4+UQ6cZk2DVE7e71AMJXgT0YAOJIxNGum3j1vA+cCwj89U42HgeY38tn7vgBeBwHkexwmnCxa40t3IGS0BRiiYUC+DOxhTIs80qwBB/SP7sbvKWtJjVU4fkkNDdk9UsQ/nlmQPiGfoGThJjryzIjRcP3zwBGtvP51K31NbNZ/Cv/tzJ45rXgwHxU9182IZ0AxKApo5R9Utq0i3hWvbC6M+cdFFturKvNzaGU/pF+B0aU/30E/ZVaQyMEI9gXOJ+R98MQcvb3nG3xrvFvFvS03dnSzOI5ZsQk8RiRodNBo2U6yZZOUJCRc4f2Jo51BItF8moqqAE+LBne8w==
    dex.authentik.clientSecret: AgDFdoM7Sb6GC2acpjgyR+iu9kXFvahGGZHwz+fMdn8uvIwuIRgkVV8SdZyeDNnyZKe5RcjkUjdFLtEnurWpt9s/pMeC8SPvoXVEacZ2nPCgGRtPl7l9fvGoJCmSedf8lC8GMKTnVg5WYmruYYz7uplT5R/N4ZucDOOnZRKIIgBVYkT2czd5+HyjHXIPzoR8NY5D8QoVEyxYlb1uqiY8MY5itVNesaswf8GZjNhGBuN2lv9VRqw4txYTds2VAccgIm2HtDkdXJ/y+E9E2FlA3ECu4NlMCcF4SipocemhyumIJ8a0rRfO8AG0YRNuIanv9QyxJlsGUWs35kGT9e4Zr/HsTVw1y+3chOhfxE58gCwgbE1dnOCEs51TPKw0DFoJg8NEmomtgNkPrGJ+bev9luMQGooiko6cPM8s/0LncealBkbnY/rb60xI1Ou1wXdUpc4Az9bjiYChyNDnjDNVgBEuHs5YBzfuQuWpkD1313eGm0zVr8IYNsfSiA9YlmZGqLK1Kg86ZwxzIq02lTG4J+2jebeXTTq2HtBuFYpEIXI+lEhEkQgBEfTLO8A8H+ULFgCwr/g81T/K7YYTyPtQGgKYYLlUVb0rdqWFN7wM71F7NNWdFfMuZOSS25huoSAR7p10qwdRWYetmsawZpgDDJ8LuW4tyDXCMDROQActJpKB5S9AoHqxzrBJ7hDrqYElUH/A8xfmmQhc61GKNyj41Q1XuG7uE4IhMcDVNA8LT9z/7g==
  template:
    metadata:
      name: argocd-oidc
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
