---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    dex.authentik.clientID: AgAxAbI14smiJeH16GEhwbg4hbRgS5ayLGv6N366MhELLRjW0wfND04Hr7hekqbjJW0bfws1qkU3rbe1XYLvXheY3MICAIEsFo2lBTJof2k7WJTzicwaLWcHpYsAj4Ahlp9Jk0u9ht20HGkof3cLDVhlPPe8oY5jU1AJj3r/tzFyWW7Vycg4pUMzKyElHCn28Ubb9/RUJilubDiD4mrIbRY+uYruy2uVWL3qlFG2CwqjVOG/xL9TP5vuu6BwbT0Q9V0NxZ77PHk+Y45sb1VUo65U/q53YFgp0859JWujdX0xyvm9BqesGdXoG1Pv4QZxK1vPa9It9Y7mzRYKCD9sq3MHauX7iLKPZeDt0AC1zjf16ARb1S4sMLQlnoNsDY0lGyfOydwnSxHLNFq02Ek8qVt+0rcl8ZJbh7m4WkRJNdk/vdCVpl2vMg3nUKw4cR6kPu05WzUTpekLSweHXsUiuO2hJaLYCDxIURjYC9yym+ekr87c/SF/Q8Va/Hn5SbFEEpDwjUUNoAb+4dXhuenMfd9KPq22B2ziku6A5bBrH+GCXxm892VdgaVAi3nYsqe2ppP9H3S9Eet6eKqv8xA7NcC6031IrHKXOVWWQCxfjeQ6r8xm38Mj4KaHSTx3CHmdzRZ9rmUekDj3pZmVvzdsuqrE4RQKaZvSv25DyhF7OzKvNykEguN7xaJ6UZoSB17h73W8XPo4bCevnUeoUohgFjbE/+ihzvkikNIyf1FQmc4P3g==
    dex.authentik.clientSecret: AgCFRFjUmAijEdTIsrlPMwl2dlpDQ+EXW+t2nPQD07zpdI5LrOSeFNwIfyY/3foEAd4LY/cMkwiNUuHPJwxNfUBhkGXUgmeFyaDsjmC4F2TPG/yWvjAqYxktSjLhMkLCkYrNfkblXnbj1oxKKFX49xhlQoUmWJbNTnpn1Ol8a10sHzSBZ3jz+LDg4m9o1ywwdE0ZZ3ho6pxroH9Rdon/vDa7DzU/ITJfx+t3/gXWMRoTTuJE5UgFE59wQCpmRMpLB/bBo615IdCUIRlLJ9430s+NEi4GDqoSuXkZA3jN1e+HnVFH8HjPiOraZZwCxX4DI5Or8Qrm0SFbUnfNj0JXMNVQcvmVdCm9oDu3shXaLWgUrMR6UFIeCZUdKrECZ1lGp95M50OqFWNGSISmlX9mxDYdTg/KY6xrawSqa/30ypl4Aq/zVIeu2Apkw0gtuoWHIaSXJ8JcTEAnCbcTb8lMvUcEm+NWrv6SWvwNfUnrnbjT38/IcM8vR33VW4u2940FBP0y87nUMPmeBccbEiQAGdPmO/CCl4Az6292eKJ1Ogt8qZ2jG83PKQc7DiFVIxT5/IQaqbjHeVX650y0uW/Go3o0cnOYV7hjc3KwKglQ85fWgq4/wHG4KZFrnmmxMcamQtODfIkX7gKbXFcjjRJi3rDKHhP1k0jcPLMDwtuAb4HAlxiH72v21JDLbikCQFklnL+xFFDZjPoYhxUhd+XnF7P+XGB5wXEqaUjnSKKLmh+BNA==
  template:
    metadata:
      name: argocd-oidc
      namespace: argocd
