---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: barnes-biz
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAeMz4nnomniOxZR4l9EqtvfZtXd+P8gdY7TJqNKxycR0hnsMEG/1DeOYVicwiygEMwKoUonqK8DnF3zzofPHSxWrucWbMGCAmwLAXnSASDSjEJbGzYml+Bopq1nmIvOKqyir8fj7uQLIvXbgd+E+Q3voUd7SdrTKgldhRDt4M43W4408nEHVzrwwQJkUzpwDeeNbcHMlkjyJr5tu09kmIugNKgMU4oLs3sELbRWte0pRkqRQHbW7LoHaiJJESsBcDl/5vTMZ5Kvj+LH/wFOpmO3aVxQT/O9VhwfUM3f2ziTow4RH+r7cBsQ5GdeF83AOsSznpWQucOTJNVzOaYARslogzGn4DhgsdhQaJAN+dfIXsq9D4Lslf00/CpPwvm+qobdgvocrlYHHORIAPAzcZjrOVv7/LMmLFUCXHh08fpdUmWg/z1qC4H23aKZPXjli64PwNRK6VMhG4c6+OfJx8TgoXGO/Nh2vZ0dV1CVILm+m5aZfB4G0mD5rSK3l/KRmYmaqvqhiBSOuURnG0+vpvvZCXscvDlBpY2th+NqGNLl3ID6Nv6yjngg6MgoaIp/WnDJPi0fT3dTjRw6BuobKcK2LahZ6W+ScrNbnTP4k6lANz0QQN8Zeposdzjtq33+cutf+ZQ6AHetCdrFdJGzVEESNb2lSTM2AWr8EiKDEVnP5NNxTdGXB+/mhzD3SI3Y+u1w8vUT32hCOO6WsmG+s8bYd8e0MlO1RQy79HSfF30Nl1H9ESxyjPBJefqK1wAz5tjPIpx31nvh63kR3Xnjh2ulTRqgJfFxS0qxLvDi2w6QAFoC4tdu+DAr+glu1GEI4t02hz0XfaWELt5Vk1nh2I/552P+ecQnKviL/auY8jMbzOsU53rWSW4p+Ai6fajpEUGyQOvuLpLYZCXSEDTT5A7WqKLgmJ7jcbmMksrkoS+OYNt9mhu1Oxc8HOMxehj9FMypN2a7gan1iN0PDwqEntRmM8+Wwdmo3mTCOX+0oMFSUOq0EThwWCppMuy+RTtmoUcZxzHUXxJRw==
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: barnes-biz
