---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: barnes-biz
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAU8m0y6WZO+0vGYG01AxeCXNsEJafU4bid5MyIyYUg+jAzpR4MhtzIwaSSapyhvQmfuq5zwNTj2ShW1h4iSc0BaB+pNtLFmwAoEgzIo9hzEAUgVKtaEYG6LwxzYTHJOzjR0YWiZ9mgMytmssFcmoXqGiRBYE264/1N7daqBKibK+97SC5fbmt/SlgBbUZWspig70I0mnH7a7SZFLoQZ64KdzHLTuA1Aa9KYytFD8cMmKZob7yRw7UB04A5xfBVe/PpFmibcRrXOZ/QeRopVnJWEt9Z9519QgjzFKwSGr4mBhgBJCSSa7tMLL984mL4CbjSHrIq/BoufkkUws1cdIph088A2OPEaj+swKneBEp1JRrghhx6fzBaQAxesDlAsCM38klSa0STXZUG4rbUWJDVzaqLBdPG7yB20Fwk4lr6xSHpvdvzhSW10rn4wMFCdoVBj78nePN8cybw7yAE5hFK4RoquSp8c7l7EyhRTAPwHMM5gx/rhixfs+2AVqM8GwIM9JnN2Sj7hLSlK3MhIYyXBa84wpSQXgkVAACtRRpyaNlijQ8elGAcXkE30aKjLqhTKmZBzn2XvSNU7x0ZrJrRPc6rXADQ3o4963NLETKsRvU0BnLidZc4YOH85x+lIdMm9+e6VjbkwVEy9EoljkDy3itwtVsuGiayX29W++jRyRUOsxhgopK8hOezz+n1NBecOEozYIxMQeiB57gkCvw8x+ZRegkpaYwT2UJ+dvb2g5dkCHkw/dbgF2kKJ+a1XpgoKYA/mA62DMwzTp9AN+UkTZJWdNQdrADvQVsT7cJ+UbADeP3phg7sXLSMQskQrsXt3hWEuDO+u9l5XV2oKMSx/1jH9bb0Vdg99YBoAXWxV7dgG30zds6dQ0Rh3vsqtBKSE7j6sxboICuJrlAcAWlhclxdt9Cz/1k31GWcueY4e5Zl8CcMInKL6y9sybDPE4Spxr+ycU2MmxePAfHhFTjUJ8BM5vdUbhekOlWMbGtBeSV36UqUiRabvZ/su3sAsH6R5GBzKFIj7g==
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: barnes-biz
