---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: barnes-biz
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCUTmmQjHX8MZphCsIjAOos4D0wTm38sfguji++YLFZRgB6+SO4LWV22wPOQd8jH4JN3LLf1bn48y/168IczgQdp+8dg69DbyBqagtzzWnpcFUUGuh5IRmSDcpKToRdICao2QppUPHLbHpnvrClLoxbTrH0I0E6JhJZAY6LKyW0mD4x86Z9HGVwmmCRHZbAyFVXbLZhE6J09INTKTAhLiZX12unEdsdeHGLbmqeBgz0OrhjeLjENtyHwTkScUglIJVvuJTDUybPXgTUUJYYLVfubjNFSLU2yaCt8uZ7r0EbVyrUsTQCxZPdmreLljuVoeMR3ZjRn+2GOxZEjVLfYSIkkxmtIh3J65jxSfNgZeAvuMaVcJ/DHcsOAMFe6rbPac92drgQ/yf6Z1uzyTGSLkeNBQkoHhUAV+B4JsrMMh0Ee9julXryBjTUbiGVvhobud0ZSjzOns5/pzGYcR57Mc+nbp8IRzr46AywrBUrm72H6pv2NQWkbDnG/aH9qoz6UiVrRaS2mwNaeTJPCqux2xaBLZRPeQ7pfvHjF8wI35+JD68NT99yqMAQLk4nXm8ZK8RgSFMbEUKF+ZzsJydkmJtmvZMG7L03ReUB1gHAJv/QuCYNS1SqQN0oBdOI8a8Fd+MHCsNns7lo4sJKmj5CBWM3pW52Upmxu25pzpOf7OyVmCobCNaJXNhhV3IQKKmEuSUyGxB45JaEqIIj2DzC0Ez3YVCoqgig+9puhMsabv3iZEScWB68i68YFElmPzF+wU1IiBMRhavKALBq2ZER89uLbMUUB2zIBw1n+KYHiPcRSw1VNJbvVvXJeZy7rxsNtxi2OI/Fdl04d+T4yW/OClRZajAhnWckpNNtwlStzU7OCK05cdWTuXKtsJ1gr7zrTf3lZ//edAITAd+D4UOLBfXQ7Rif0rKtq6g0taj+lOt1cSMR6Iros3D8m6uXrzRESpkA1mAgIrgssNXtt52F6JIqPfoc6eXvlZ1JwJ2tUqKoiagpjwtJmrUn8TP/A7XMfevdBKIAF5MVpw==
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: barnes-biz
