---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: barnes-biz
spec:
  encryptedData:
    SMTP_PASS: AgCBGacECEBilpyv0R7qDtj52dqw6eLhoH5b4ip1ni6eMG117bsz0sqHIr482p10ldV9zEiGO5i5R/sPOvfhU9gA4f2Z/yCwCcCZy8HQoXVlnoJ2Cukp1GdEAZFoZtnh31KCkOwHlOT5CO++g2gP3CZ5kxf5FrueRaH1vAubc3uKh2e1MrMvSd7/yPP6TTVnQ1TLtCyIVu47QFAvjc18ynReyIDKTRFe3viv2jJCwQhjdDY1Mcr5JHdt3oBdLbG/0ve7e5yeIkF6iIoZGqm8ZxHX8kyNTH49udk/vldlXQJnDB/mHX4l2LhElvcLHBqgixZMQr7B8pYJw593zBj17R9B56A0dK4SBDCU3Uz7aRCLMIvWYNIhinI51oWBgD5dCBwMGkshxwweIFL7d2XctZrGpIJpmhVdCO0Y83odv5zqWkxld3NhHk2YjqQf/BxnSfTzJEe/EnmuBvkYjMhbBI8LhmwsbpfsOcQ/f3ZWf/++72vx4dHtfMk7avXKAYdUNy88LaSgzSfyDDpxVl6LwqXL44AgpqpaSpm7lxz2OQ3qOiyHYRcQ3H9yS/vTn1TY36+oD9B2uZX/2oENSJBRqQymcyC6753T6fv/jsUq4Vax7CLTyfOWKjJE2O1oDqeT6xVrPPce25V785mHUjJaMbZVVs34/sdZYsvJZKc6yKP4T3mxxMtwA1RyYj8H5ROLhKa97kwNQORVoGZw/5u6JKigzohp
    SMTP_USER: AgDG452kiuYwlvzzO1/WLKSUEDT2zmoyvrengGozHi9moicZrhgJn/7W8qhz59QayczL8cUMAZEmKPpGqSFm4ToS6GZtgkMifJGXAYFW7rfyPCl8NruaAy+fZbyWddX4UGjf37hckG7AWgM42gW34CE3N7OvEpbPPWWXMJUlIUSmC8l0VDACk+gChqYLBrJzKL/ecEA5zDlymFl9vIbXu+0BM8IAA3mDDKwpfvhk3XXgT75WcQZ8zWqIQ3us1ypH4s/t/edcnZbInR7oHsjlnpEKrg26s/wqYFOlgZVnx/hLmoKIRvC2MmpqmTHH2o6mvoB5dfhJwcKuNN+ODdxOaxgGLqMW7UlN/g/4cXev7cNJHOEdd0ka7pe6LnyGCIBX2QUTNJNxwiT1sEWxEZOv3Cz0dSLzYpvYwVsBr5igZXWiUP8Zbs7RR8NFVMsSAEfZhOecrqTPCketotitshywmV08jhPKc6Kh2ZmnPjf+tnZqzR+yrKA4WrFJzKA1DAZfc6KIMuOyFuTIZTn7bBP2oblpoWUL0nRoX+Jf9VT5hDEocNM5hzAYtKfB17hyDgJAjaEU1hvJ4CvWFvQyTJMTOce+Uf4taas0QzOHdaIBLJridhxyYnV5t0ORnEenraWXyQCv+TESNXHtaznDdhXMb5cebD44XJcNpnJ93hLCW5cCOExX8JELJqGW21miIhGWtEkL7dlxntMIsQ824gus7Zpu/incOgVQ+1gnh7xLAecz
  template:
    metadata:
      name: smtp-credentials
      namespace: barnes-biz
