---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: barnes-biz
spec:
  encryptedData:
    SMTP_PASS: AgDIqYpDqcI0gnYvA1Qnd9ebi1bkn4+TLM9m4UIk+8g9Uh+3n7f0lYGnqw5tc4l4VQP8djwvoNcEKwWTi5pKQE8k9jgGv3EJobFR6w4SzOzmBRHgv/ZAgoP+5Rai3EygqudI9o4maW2FwQuBom2WkDYkdeMf9meL830WOIBwTo9B3O30icOSIJQxSq0LGVbtN84ZEdMoeXJ52GcbQXA79spNv/KjDNkoOO3f5IeuPvkbCopgcOK0Z5V/J4S6DKvP8Pxjq3t4G1R3QXBxrqr63wWflJqRaKSbHXLokNy6lg1bhPSub8daMDrm6IdtsW5R8IupD+usGshLeuXaa4Cl4UGYYx9+ufKMhC4q6swNxzV9AnaylakV6XJXMWuhBRW0gwlLxWLqc1XNAhHQDkJEuA4MEJSwOZfId8wGME8PuG0nIZr2K3dD9Bgb4SuYczGRykMMvM3b1ztsqylIxbFc5OKA0EHh1qSqHYnc9L+6k5g9+vhgsAeXDbKncdrZrXTxXD75ZUtiHcHVQaC+N4S1ZpjdFij2KPn9QsZzprn8rWATSctZQtiyp1lk3rg6QS6K2vpRk0RSeaGYunZlym8uvbfI29qz2ucr8plqHdH/hoq+6Kkp0FWKrTt9e7iEEWXhCW6D71xUYk7kCsR4GKFTogGsZ4bdUTFDPXfm7ufYB/RVF5O1bnDMW1lNcplgBQbgbj7e/R28yFrbHqAdtK9gPdrH8PxW
    SMTP_USER: AgAEAWaCdQxLoT+upTzN07Qi9VD0kahlcKe8fRNIVp3JvVi//fmDbVOJz7gR2ukOIjgERC7O6JkqcKMiGiWWnj3vQUJfwkEuEqj/xuPMzGWs/QGvEjwLqT1Oxw0n7cqRcFUBGTlt/IbuuV+sE4hNGvRnWBYtEvC4GdtWJqZEVcK7zN5RYCZBGRq0s9sWEWy/GDpjtL1Uq1EcwzfdVIsfBiB9cn1spEgzSJ5ngWkNKH6fw10od7pXKskelAsY+WMcNNZKmPEeXnUnc/FfEj9LuAGs3MPYmP84PhpqqB5CuYdOsrPr4nzhr2yROhcyO77d5wMIsA+P1eNmYQ3A5/ZSaKgg5I9oMq+RI99ycapRHNE6Oy0hWgLcM34BJUqqJT7CDTPAjk2hItn3JMMPN38FYzdNhQ9jiGC2g3HYRxJBAe+sZ1bDKMABnI67toFliKFtWT+wGZS0wBna/Lk1Xysl1J8AEIkdj6BwulHajK6ZkLoZXA+99VNbbXzKVppdUCIKdYfCTEapwCthChAP4XRsWDw1AK+nhUe52O1oe2WwlTUHAbJ3HE1uk9e8wphaCU3jufqi4A7kjvXUYVMrJy49DxDlylrjemy4DdQAduaBc6+KD5Qxuc+Gnz7T7ieOa7o4V3+/JPMlcYN1J6TihLyeQvqXNTgCU9EunYVp8LPeQIvQurJiP4eq6zaLFDPkbfvb8+/ZrcVRnAEkndfcLpTQYpyDStC3SMtZEL7bGBvkrE6Q
  template:
    metadata:
      name: smtp-credentials
      namespace: barnes-biz
