---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: barnes-biz
spec:
  encryptedData:
    SMTP_PASS: AgAzVCqn4bI351yKv2Urq/IAbsVNvumYF7s2pUx9kuMtuM1D/P1nTBE942RogSpHqdhkKV7eBlICxCLtATpv0YAivD58J2HaecFHFHgd16AOMK9ekBkZnHGjyFcTUAUPm1N6B0FVoEmArXNWaYfBljbA0QUh8KA0YYlmALzPdTyMaCwl3afVNCt/nTZfq9idHwCmRigLDoSmclB9OZ432G55YkpUPgRPFMxedMXW52R1+PB7OnhwvRRW6WX8o/I1OIlKcienTIq1Hv2AGGjYH4vDILU5m/jVvXbsaxwslF3/06XHEo4CuSM+VjqrFi3X0hTc/Cmamhb539hWLLxNwT5ux8bEAHNKQ6nXNoGcflQSpmYdhhDf1dCMDAakeAu5Mfu2JDzVzoT6q3zaa8OAGvIxOpzCIs8P4gi+n2LiZp9xIcTEhqoS/aAaJtnRGbB3i3f4ysKoWgThKfWj5aP72ur4uXwjKTvPI0LEaZHBQ82+bTbDW1tFzWRMJfDU41xhXnsHMDrfhLSMHKAUippN5+bnwy7NH17m5qxwxeQOywiDzLrzHgfktNE9nQUMMEZcQ6Y2v/qhiIDtagiINSeglEhf/NCT3JB0bEauYMYQOshUUbT1KTL/KTZ6NUEF4PFUrAdNJNKLCxb5PrdSqToXEpa3LPcLjwRyc8nBPOlYtonpcmUuKf/hYb9BO1hyTvZrt84V3TaUgJxOhZvMkRFaKspL6BVy
    SMTP_USER: AgBrdcKD9KtRkne3s6D4Gbkg5XewN/vL+p/Q4ufLU0pmiE5mjTR6jmfqt/0r6L9AaAVE+EbQWrj1nuqv+f+oqMWaKewE+e/dkBHdFfhK6jb4O1nc7vONmDiBs8zN6mvVtn2ScCtRUOEzhPv+t4W8KcKXlSRevzLQ81EXRTCNiqG7i3O7kGWMJs8TgSyjR4qUuZnoQYYxozpduAXtq4nBRGRpFzH0huE0kCStglpt738wLbVTTeMh3DueSn/stBOhX0kcAO6E8e9W3f2JyhFaom8ykuuz3zRiGwkLz0U3JGL2RsHOpqR21/ieHK5gkKKc2x7B2kUELVfKkKMpIWPqRT5P15zatOFN3zRZlGnudQXixLGf42Kt39ABYtc2reLYoHswtlV4S9F0tdwBcyePGpXmgByi3H3j5H2mj7Wek4MiyjdnBAaW0bpICfdfTJE4UydD9JwAgJqXsyOV6WzHG1YYpkh8gsjtVauRNLD/d0jNEcdZfM/VY76r1efVLd1sBJKACnDMWmfF87Nna/9FvGZTtVdfEa210qojYQA/JoQ+wsNvZSjkyu0DaHqj9cxvC2VNd5JSlqnr/SZVGkK0xl5F5aH3N3Q/JvI/A7wLrjFGurgaynZzf/5OvOMfh7QuSt8QEpwG9Efzz/rs2u9D1KWGOG32tFjaMHBk8EgwIulg5+JFs8NSF6F31K4iFqtTymF7opcsu1k5RHBF3F98jzKcYyP/ssXE8CEkeK4VuzRJ
  template:
    metadata:
      name: smtp-credentials
      namespace: barnes-biz
