---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgByRw1V/2bN31OfgBTkA0Hf8DCHiR65yACRKpkvQ8OMYACW5lsKM6jrPu7XsdVnxUe8lXXKfCkkw1qdkhhS7lb6I74/5bFmSgVFcrdg87QMMYBwNEPa+rW1ShA2gSCUgAZRHTCmTz574vXTT3KyOLRl2MxFRx4LpohONKpx35wpJvdxsc8zwWejzHJCZT+k84huutwEI92vanGkUBzOJcvhPJ0rYaKy5y8BYehhhSjfX/aJw7QPzlFASqoPdKxcVVBQozfg2zRszwxlBSi4HdmPYx33Phjqn9tsRgKMRSP0RumdaC3vGMqOzD1jxLY7sLa77GXG/6YFT07E3taYtjWn9lp2+HYpeU3bEvMXktqHJZ/FBDZtty8p7ypYlMBGcRQ6j5SVhjlbfQxXy/rIyBrYyIQc8AYOJHs1NwQA7hsmtDc8LeRc26j35HkXjD4/VfX9gUoRDZaWkxIY+4AFxyYdGq5P/2H92Mc3+CIavzVS0k9Cx/nXL1qDVUJbQGraB0mp48AViohBUYBax5UKHLvqDWCFEUrX1s1EiGoDyHmcoHM/9Bb1X1JvOCdESSv+1UqCJg11fMEvE2VEmI4J8tCVBg+BHMkC6Qx5dDuSQqJfz8oBVuBUTedXkgr04XrRarJDmcCtXUBcePetReUi/huKJ2A28DBl/AzN1bGoV4l+qvMiTgeMEtDbWInj8TDmPOY5nC8EqQMAsBRv+TsTy0Fut/nPi7e6lurOqsWdYLd+0Q==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCm/5SQ+ikYf4XaT9/05nZyUKT5oXvHDpHlYBDAUJaqJtgRuf1l3dJbqDyJBKzizKN7C/b9Bj8Wv+P2UFLRXrBQnfe6jitDHxnVBVt08VGEYICke8LeL9xY1+NCWh6yfmln7FlXfJVnsRNVO+Rip/SvtE+KoPqbc9id7qFkW9CkpjshabnIADMqvqr5MI93ZQ5fwZJvEl557pTgcakpMYjy1hLTrwepTExpD6Uvfz0CLYZJJAVwcGRNldK+6oPPdcGXgdYQv6Ls0KkxaYeJnhTEH8Qd7+OKex/TCxvf3Ul5xosauBxK69YUGvAzZ1LHtMg3kSuZ2EgbxcbUUR416W1qAYoAEa6PLjOwBYQ/ru8NiX6KVYubC3vLMWpEBldpNAkyOraUzYfIhaVV72vzixr22e6tIOykwzI6n/Ry77WIStKWhkFuvV3kMipZHNIBMvzQsGwI9tqyqMizwVphVp3MmuheNedSaPuzfIoSSUdjcUYkQvIzv78l20zaaH7i0A83GVUCe2cyT/hQ9dwe/0Xg+Mtbaccy0xmDVr2wC82RxeXZUCfMl6tqmo6HJRmJ7ytg1uhDYz4K6syTql3m2pdS6ruH8TwhhQfDXqxTBqkYFJGMeLprf5E4szbI/HM2PqwVX9eVKpCWc/C1n7XtMyAKcmuy57th5I0CMBcLV+ZIP8R1AexVv1NMwdbzDcy6mptutlcACxTxxtoI2poN3GzHuoJqXAeNQnZD+9PTOagUlA==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
