---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: AgBQN0amtPLHsEbNG3MKxtUtkHMX/YqPkNN6R63pem+pXgwzyfdvxV3KMEgxDls30YAV5RhEmJkt+g5p7ob7E5lwPBSNl9f6w8YAAsTyKk5EOGY0/MpsFt/c7h+5YgTgaTgBRIrLXKPTAyTIeIMRx+Bv+qIgwXA/otLBKW2OXIBk50GkHDAiT0p83vzYdgN5YBNe23hQmMtHLRjZ25WPp1J4FhiFgnSfB5xHGLe4XrU0ZWTBq8cCD+vtrOr7aGsOJf0F2ZNi3TQCJLsDLNWl5LVRzS0oXlIbegfr686smgrddyCk5VKLCBgcFH7XNZy13Wyp1/TdXsCjgFCbXDxCbiNJuS8E/EWPuccUg+VPmfklBxfLxPaEzV2eZdfQpbLDM2Oaf9WaaHONZjQyzjkaoGtpdVG0M3eYDz1RWT3umlKAw3nJvL0nkkhXohoATh825kH+BHNVNm/YPcvZ5xq06n3rOC3MMAorKecaxgj3uJaHDh7MaD1ED3GpUgRn6sTM7fJssdBYlUIwVEB861mK+vC8/FFgJcx9B1oHWaZurCKuyuX9Xk/MrQJXE4i2FaWXKx8WZt8UztdhT0TVgmrhbXfKIW/gujckFQZLWKNKltEitGy6dcvHhwIgGjt8/PpOraakGlOqiQGmi8T6zspVv95rgMmHLoD07VyA+9IWWiFvWRyQ8oQTyiU4Jmqg8xQeF/Mk7KNwRU84DR5ACTzApEcu/e4MrVTYWptIbz+pi1RTHw==
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAldSfQLbvSzBqzo8GwYcoQqH6fe9OI4OQJvLa7zHSntQLr8Xm72z6eFvmlR6eJwO7w1p/Coc6K2r9Y8gRcF/RLByqs/tb2CKpQBqhf5sZPhUKCDdix+uQ8fWWbpcWAZ0Tk11OHjk7tJasET3jC0W5d+bZp0KX/H0FlEHK2J+z0ZeZX5nGM2Qcd7t95z5pimBGT0lXXWMBGmI0ncPXYDS+7rK5xgQDjNv/jfTRi0PMYx/sd3yxfciuercDcgqw/fDtMZcStm/cqXZvTHNhLK1+UbLqQKCV82cJlOkwhqX3NtWOzVMgQHe6N4IaLAMkjh80cpKK5FzLCk/JGGA3Dx+lEFQ/WfkV5EWjOVBIFBdRO98gUqcCzERrrqECdXzk9yOCkQa1rD0/8NVzacgWHEjp5fqZxTgd6xrK+PfaEsn9oFaFJeNym4MPXqOU8aOIIgYWBHzeLB80dy4ecbg8H1OKWwht1Vgu+F6Ae2DYFtimoxUWC5SJr4US3dVTFoOGwSJn6MfFRfSuOOGi+q6hDoIXnPacZsY3RLZNMMOswFRGJjGxJrRNjKccANvjncUkYpoVx3R/LYblsnARRFaXFmbytW2StD1dcvCLhPx5yURRlD6p6dqnm58BITSRB9uLv4GuvqHlJz8xFTGsYZMiggWSi1+vpkcpdFYyZ84Rvwgp+c2aOBua9VSWbolA3JExao5Nm+BK4aX+irfc7gK6F11+a4eoS21dWOELtpyWHh//VgA==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
