---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCcDGEJlomKkxDvKYKWiUf9yG1OmvnvKbkP8JQwVbjFme01adMCl6UdJJvoWO02TwA6+px61uvVZkJdpBZiNV9HyyU1ikr5ZWjpw58aOb3BmvtIIy7mO1lcgi1V/xSXnIyDSKTn4VWitXRCQ7Am8QyrxbPSWQSE1swg9o+JpPMtZSiMjxM/+Qa2LFPHkGBaHje9QJRNPpefG+vOiAU94gFIebz98tDiwuHc4RVcKL0R47ZtrL9CoZmYoDu15N+85B1EchzTw7rKM36eXCKnmJojUQhSoC+z+nPDyEAsemnZSAaMFPmMqbGkH6kd3c0YY+KDZXWT+9iPKAlLNYv2XJeWxnm2WKnaq3mvYYjwU42FkX3L/EXxDSuE2oHh99L6ZqvjifoNNAnPfsHkfcDpH6i0mBAqywPkjLg4cBM1kDk4TjwqHaxg0k950xPMUWtyYpcyYVyL6HTrMIbcazcbIZEIEmDIVwaFaqZx9GbnYsX4VNcSA1C4/Vu++kARmC/OOYA0SeSj9oXtnVdy6uGk+UrKjDbV+ra5h7dfZD9Ic4XbLz4o3HsF2w0OT2dDyybxAmexh/e/SDLynQpwnGzmDxoqSwlLL9SJpixyHCktBUfHmWCmLs00N2EEZUQF2sSV+rqGLxzzBe8aMIy6LfVjz2UyDtQ2wRa9JERolKSHWIygkpOEJxZIxJLtD4x1symvXGA5GLJbKEpB5e/ApHWDXtbc8+LCAZX2b+5gdzxVeMLsgQ==
    DB_USERNAME: AgB1sllJYIvub1ETuhzWdSLsjGeN6MQp+mNwHxszyTSY1VOtwSmRHcWmgRIrJKpgCZo7C+SOImiqoZFgLYqby9iO79F7jHw98yXSTpTb/3xDAlzhyUqMn4mHumjtPOkeUgZEHn8zJGz1txcA3H07kN793cw+pmTNhmp2XgdBacjZYrtKbr2SJdYE1IS6LI5YKIiQystcHsE4P1KcIeQ10XccAbdo/QnWzN8XearPrKv1TcuyQOflWWUg02ttfZYQLQbC9khylupprSgmmR11DgLiEZKusfH08apBSF8gHtj+oh3EQ6eqmJ2tG2Ow1Cshhz5PX21J0TKpjrLysO+tkiii0H6ndCQ2l/pYw+gZyKsTfypQfLAR7gvweCqb3+Od8EM73gfOy2d7H23x8d7G9x/wbRvJAnPC3aq+6BFmVXUzXYN+o+0YGphevCVOj05h+NHkU0WPUdaQk4MPNQo/ME6LablCxTvqTRqWkSgskTsbY1VHOmM/uta0aTEXaGJFB5KEbs5+MUPvMIUPBm9kr6ldJSmDXb0W+JdTb/i1QpcpjyhOaArsy64bcK8NXnbeL5bJPPW6KkL4YCdZinDi0criY21+ayMZn7y4brrO0uGdTU2jvoK0Bveg/Jk12Ns61IdI86X2KjRixsKo8vS6NKA0eTFDOsTf7sqz4JKD3XD/3zrafk+6dkXrqvFEider86hJxceCNIbr3VDoGE+ay0UPntGTqShAt887gk7SoaxHLQ==
  template:
    metadata:
      name: immich-postgres-credentials
      namespace: immich
