---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgA7qWkc+fQn7Wn3sQnKxkN3E0Y7GMp3f+tqs2kKLkpKf3R91z+P4QcpzCFif8NZhLZ+J844O2ZXsS88GjPcvtAHBvF6WNTAOBdqCUd/FDvoq/6ulerAd/ZznRoFhhrDY+w39vHyJH0PwrSxWIkVyxvj4PBZjbL7Cdz7gCRbq877vBzthPvrRAXLETCgpDL8KBmU2rt48qcMTgP38qwEBDN6//wMg5cFbVy5lYS0w2v+PDAYII4JNNZaAZUOWyEa4Jj3XJSwr4SPg8OHvQdMX9Our3D9oG/L1v65tvaC4H2weNaXfeCpVpCopH3fa23K3WjSKbJSrVoPIn6TyGsRD4kP0zLsHOBaWEa50zuMXTidrWzkN7wILaQYCFg+RE7Ps5QlPDlvhFQnQcdE74exmWoxm1xsEatGY0OXrCVKP8+e+GE3JCmpugYW3RGXCNzaTuj+6BKMS6CTWHNmjqGMQL5czwZdpUOceba1ynPFo7KYS/aKza1wu/jX0i/NGGzRPMpy86DCiI+c9SNouoyZOa/B5zS7KxQK19gHSM7ddzXfN5AZ/1CyRaagcHyZyeM/AycLdH7qjiUQRHxzkLkW8zbp3FgG515QIU9RYnf4Nr2hzQttz2uqEn4uHsdgCU05qJOG3V84HRUi11EbOV+U2o1E8wG0GEM8NYDpKgFGkTGXugFJvFLszI9hRFcXyJktvuQCOaDTzJYxlFS12EsTq8k0xdgnNC/FZvYbmxloXNwBQw==
    DB_USERNAME: AgCYnbm/lqoWUm2IugndvadxcryLlA2VltVlS+Gt+510d11xwZlU8n33vC1ZvCCvXsTfGMDU/pcbOqSAfyLYK5XUOHahjcQOrem7wRQ9NdwKuvr1mp67Gqw8cGXFG1ed18f9ZpwfDYlzddVCjBJQUpLvwkVgJjAY3G/Gowb688wz9+ty72aq4qZeJO2Y/yAR+gZxA0bvSA23DbzbmGG1+/OuvVi1ogyBEwDOKKdVtgUpdYfwQX0qiV+j0DMki5ghUHjpwaQ6xTNmkm8BOCzx27QTND1N+5ewmmIX7Zw/YbpZj7weCuhyJHP5RR73g3/N9mEmQDA10IlHEGpofRNw5Ycb5xv4ofwhvIUwGhYcBCRzxowcMI3Peru0/AnDxYz6qwn7zXqAIqiJbO27WZm0DjeVkzeRj/gEG4C5xC5otJ8U/Ig8tQfpYRFUgddyM0E0VwyduNwcD20VbleiIuxgQ14WlHEhxB0WfoplKVnPnSmWW3YmgpoTPlhxQBrKKVfxxrncDcO5pF22mEmISS3iFgKJTKe2GUo7zNrL3lDfCOkZuaG7okMeA/gOgUeNFoh8FVnOgYYYa0tco/lAV/JbaNUfM+QcHY0+DB+STFMOjw73RqOyjVxuQRmJPwguNZ4cqgaiRGP6AXa5b6ljVfw5Z1FH18BZnE9jDnwJ1zier/Kd9r7tS5gkUVQQr4+RHpJ4qU9fHsunYmyBtwRAnPTlvTpYAnweGZCJ2Xo0nf8B/BvocQ==
  template:
    metadata:
      name: immich-postgres-credentials
      namespace: immich
