---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCZi+JzOLsBS/0PMCRd/a5sC5Cs5/vX2va0vqrXczgixOzHxs6GzTZ3sJpLHzLD9t6NfdayZa4f5c4yqS+CCK8nzP3SGf/06XInzCkaBWpbQaRBHsVjQyqkxNUCY47ECL0RDa47jb1OYzJJefhU/IVL5QJS7lRoA7MXJkwJeoJBYRk34F1ULvcCYi8Lcr3fT27tAXRv+HTl3Ee3/1r/2zsDcOptUoi3mz+Ku8R6ktUWeyKKh4DUSlN4jsDZyNjDxOycfGqdUJWGhFRGdulhdLiITBuJJzie5wXXUhwyO4STHbIJmHSr01SgaCvFrOTxPllNh8ck2F8VHYI7lJBjvNiTTSPGSrp9TyE/fq43/xxO2Dxj+2FYN7e5k2nz0IRx9Td4E652obcRIVOY4ZOh4U2gDvZ4GEBM6tLmrWibodoRYzxXDF7IHyduH0K9FAVq62MWd9MwN3OObkwB8xBfI4raYIYqeJGP+PKu5ygA5t1tAY2cIJ7cpHOIRlPVdJE7hDBIdrVLOx/AF/yYZ381+4nSgtIq0gqnIO2tNeh24OCylUiskIGIZ6+3DJD1fSTaEM2tHYkUgymKZSH96Zaf/2DeYpr8o6p9Mu4BCuwkhhFs3MYgO2B4kk0nIKmP16ablgRaNGmPCecaYB3JapO4bZAmA2PTxE7+FQtYUdp4IJk8HGNbQ4SvEpy60cfyUN0WdrJ5Qsy3iSbEP27TixDxZ/eUfBcMqa41RRXVbyOgajXDEw==
    DB_USERNAME: AgCTN7zYATAtb+2F/Hzqk+E4CP5NZRhn/TOPNau5I3z+R4skXbm+nUSSlCm2tTmPeahsr9QC53df/BoSUMtI0HfcpnEYPIDmQhgn10YoXbXBT/xo21/QE9Bqk9OSm9g//MXHQvekpOE15LrnwjDJJ1YtfOfFXgVf4xoeIoV1ssn5WUkJLeQ2lkZDB3IlU+QxLDmZPRSMkv1dkTE8HbmyTwcp4wuVyew2qMX6K3nMHbngqOrXiaAOZIHsYnKM1Hf2fsY3wqp3c6iSSQ3RPR0e2SJW/aIf5oj4RyIwyh6tTNjGlPMoxWLiSNA13e+Tp8hkDGEON4sFKmPtjca0Gs82BYsXnJRBMYMhsF9EypyJJeXy1ZJ/P9+jYQ0HdVQ9INgxh54OSSTc7JGrCPbomYjL/HR5jAg1FWdzuCmViDqIgthaUhYiUxkwsZ4JKeUlcebz4rR6duLVRZNRWt7odGXLoSDVibD49xt6LNf8mpj1xYZDRyiOxD+ggcQw2Hq0QK2SNekg7mqhQEvw/jkNVR5v7jbZSBhYoHKjizNbEib4AX2DtlAVKTWV5Dva8AuZU4+zH59hcOfS4ubnvaifS4pnYVmnvjDypYVwXGUB8KS21aqW9HvuZvnJulJdFyKcNXqwoaqXfWdhI0YQtIAOBwwO/W4ok6smFs4lZeRONb6CUiWwIaUMMH38IZo2tIjQwT8gcGkp3L5k4lOlYwn9jA6S7LWS1NiJrXzpE70dFfJ/bgEMlA==
  template:
    metadata:
      name: immich-postgres-credentials
      namespace: immich
