---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-config
  namespace: immich
spec:
  encryptedData:
    immich.json: AgDJ6e8RM6ZBaHBPUn46XstfVQ8Qi9/vClUwrpc5xPlBGl12LiD9Gfd9hQgjEohjHl8snVsXQJpOQrxcSrUUcK8x3yslQLTKuj6cPt6A9tUKyYsbVUwC/8uC/oJJS0qUjWyihL9QDM9fLV3diBvzOqJOQPN9FjSNMRdYXtFMBcdxWfTVr6703+wuzGdMCWdtD7scocSa5rP5p/M8kro/d6sOCiqow0DQBsr+a8dl5HYDXsfw3NKSy5DyV13WDJMOsSpDJelbVRTGAeE1XSvt2nTl7Y1xX/qc3YMWrweC2iNckKHMECe4Q1F2ItAiHq/FctI8BBGfJT9zJImLStnrgf+wa0pbB1El/RyenCwaSLJoFOJYsATz5/bGgaBer0HMzsKFDCfx7ru93xDsKWazTHsocqUrqMyaP7ex8mTVYxTl4bX1JNM0LCP+QEvZv1+SQWHBRo9T/T44qXUUP1UJJkzlSs4l26EeTXzcah8LkFAfuyFEYP6SRTg4VMRai8BrUutxeQFg8mlXdwj9OxBuCxxEzcFVYrYAAwmaFMImTVxRTef8R9l3G6vIqJpZKq1WziOf0lUol7pKHWsCHD/SiVxTm3qr5G0hTmehj7KdERYMc5dDJ1o5UFurK1EMw758kI1LI9q2QBcKL++HRlHFuHSTeXo3K7qMkwXXAdTpSlFfOSDiyjFOUPVZ7dYlHNCRYrbVlg4pQnE/jBqhGE09Q5ZpkuWvNpJJQ+IDxJm7LzU3ozItqg5qxEX8XKtYZbNI8dbzBhW5rYo2JvZiZSWHbavBX5y44bEsb9LlIik3fRDEQkBIaeDecqHeBLeF1tv1rp4z8hwDMjDMTSIh92Uo6F1vYwiau63KuK3ll3h7mwguRPJvtcn/vi05i0pjPhPpK4mpccHHKQj+23zpkt9zhc7JchPGPrzswKyofJ/EBvLFzbvumcIs+R5cNlC7kJFh+x0JEd5ugw3P9QoIJxZmxB1EODEmk+gSnLbQ6XG1mZ1sDhlZu5nFoZXY7H0m+5T8X33gGY49PuXujXMEoFIts1Sk0lVSDtxhwhEFFbW3DqWayUiOIEXYshxp7ZIfLNNZKpWlopPWJo5/2bkxj26mGwROrQFhMC+SHF5Mun3/wHxATCe2lagdr+2LMbTwFIxvbAds2qV5QameMyT8JTE/2JlqUUt1gsEY1nk/7vZfrPC6B+fWIuRgUzKi+5NOExE=
  template:
    metadata:
      name: immich-config
      namespace: immich
