apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io
    chart: cilium
    targetRevision: 1.19.2
    helm:
      values: |
        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE

        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup

        ipam:
          mode: kubernetes

        kubeProxyReplacement: true
        k8sServiceHost: localhost
        k8sServicePort: 7445

        l2announcements:
          enabled: true

        gatewayAPI:
          enabled: true

        resources:
          requests:
            cpu: 100m
            memory: 256Mi

        operator:
          replicas: 1
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi

        hubble:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
